### ISSUE TITLE
Summer Analyst role at Morgan Stanley Update

### ISSUE THREAD

**Issue by Aasrish** [pittcsc/Summer2023-Internships#1044]
The Summer Analyst role at Morgan Stanley 2023 Summer is here : https://morganstanley.tal.net/vx/mobile-0/brand-0/candidate/so/pm/1/pl/1/opp/13399-2023-Technology-Summer-Analyst-Program-Mumbai-Bangalore/en-GB 
Please Update it.

**Comment by efeyakinci** [comment]
Hey Aasrish, this looks like it's in Mumbai/Bangalore. Just so you know, this repo is for internships in the U.S. and Canada
