### ISSUE TITLE
Akuna - No visa sponsorship

### ISSUE THREAD

**Issue by fuushyn** [pittcsc/Summer2023-Internships#1063]
Just got a mail which said so.

**Comment by owini** [comment]
Updated--thanks!

**Comment by SS-YS** [comment]
Akuna does provide sponsorship. The job description says "Legal authorization to work in the U.S. is required on the first day of employment including F-1 students using CPT, OPT or STEM". I also have an international friend who just received a Development – Python intern offer from Akuna.

**Comment by owini** [comment]
Updated--thank you!
