### ISSUE TITLE
Add SpaceX US Citizenship needed

### ISSUE THREAD

**Issue by sanskarfc** [pittcsc/Summer2023-Internships#1170]

**Comment by owini** [comment]
Feel free to create a pull request to contribute to the repo!

**Comment by klaireklaire** [comment]
Hi!

I’ve been trying to figure this out but I’m not too sure how to create a pull request to contribute to this repo. I cloned it, made changes and then try to push but it didn’t allow me to.

Warm regards,
Klaire Pham
