### ISSUE TITLE
Paypal link is not effective

### ISSUE THREAD

**Issue by ancientmodern** [pittcsc/Summer2023-Internships#1219]
It seems that the [link](https://paypal.eightfold.ai/careers/job?domain=paypal.com&query=intern&pid=274890684413&Job%20Category=&Country=) is no longer effective. I also searched on the Paypal website and there is no summer 2023 SDE internship available now.

**Comment by Zmwang622** [comment]
feel free to make a PR!

**Comment by maxslimb** [comment]
@ancientmodern if you scroll down on the website, you can find it says summer 2023 internship under Internship Program Information and Requirements.

**Comment by ruidazeng** [comment]
This [link](https://wd1.myworkdaysite.com/recruiting/paypal/jobs/job/San-Jose-California-United-States-of-America/Software-Engineer-Intern_R0092168?src=Eightfold) works for me

**Comment by ancientmodern** [comment]
> This [link](https://wd1.myworkdaysite.com/recruiting/paypal/jobs/job/San-Jose-California-United-States-of-America/Software-Engineer-Intern_R0092168?src=Eightfold) works for me

Thank you! This link also works for me.
