### ISSUE TITLE
Optiver doesn't support sponsorship

### ISSUE THREAD

**Issue by JueWang268** [pittcsc/Summer2023-Internships#1236]
Just got rejected 24h after applying

**Comment by Wolverine1122** [comment]
Which location and position is this?

I am in the interviewing process for SWE internship in Chicago, IL. I confirmed that I need sponsorship during phone call and still got moved.

**Comment by Wolverine1122** [comment]
![proof](https://user-images.githubusercontent.com/74157130/192107834-507116a5-c192-4b49-8558-17d2b5a2f0cb.png)

**Comment by JueWang268** [comment]
Sorry for not specifying: it was the DevOps SWE Intern position that is "not hiring individuals who now or in the future require sponsorship for employment, including candidates with OPT authorization".

**Comment by owini** [comment]
Got it-thanks!
