### ISSUE TITLE
Contribution Formatting/Style Guide

### ISSUE THREAD

**Issue by Casper-Guo** [pittcsc/Summer2023-Internships#1255]
The maintainers might consider adding a document outlining the standard format for future PRs. The main issue this will address is the unpredictable behaviour of embedded links. An especially problematic example of this is the link embedded in the company name redirecting to the page of a specific posting rather than the general career page for companies with multiple available positions. 

Proposal:
- Links embedded in the company name should redirect to the general career/internship page
- Links embedded in the job title should redirect to the specific job posting

**Comment by owini** [comment]
Noted--thanks!
