### ISSUE TITLE
Potentially make the links open in a new tab?

### ISSUE THREAD

**Issue by Bnjoroge1** [pittcsc/Summer2023-Internships#1307]
Gets pretty frustrating having to go back after following a link.

**Comment by ewang2002** [comment]
If you're on a computer, you can try right-clicking on a link and then clicking "Open in new tab."

You can also try pressing and holding CTRL on your keyboard and then clicking on a link.

**Comment by Bnjoroge1** [comment]
I mean yeah that's what I do but it would much easier to have it open in a new tab by default

**Comment by NoahBres** [comment]
You can ctrl/cmd + click a link to open links in a new tab regardless of the link.
