### ISSUE TITLE
Bain & Company no internship

### ISSUE THREAD

**Issue by hui-mu** [pittcsc/Summer2023-Internships#1367]
Link directs to an error page.
Can't find internship role but co-op role on the website

**Comment by ewang2002** [comment]
When I try to access it, it works for me. Are you referring to the apply button not working?

![image](https://user-images.githubusercontent.com/37031713/195400202-cd881161-7e73-4f09-b613-e87bfbfa0851.png)

Can you show me what you get when you try to access it?
