### ISSUE TITLE
Morgan Stanley role is for full time, not intern

### ISSUE THREAD

**Issue by ysahil97** [pittcsc/Summer2023-Internships#1373]
I checked the link for morgan stanley, and while filling in the details, I found this page:

![image](https://user-images.githubusercontent.com/19690506/195480949-e210e77a-f0b7-4b61-be23-c7aece2edb18.png)

I believe that for any internship, EAD and OPT related details would not be asked.
Therefore, I feel that this is a full time role, although not explained clearly in the description.

Could someone please corroborate this?

**Comment by ewang2002** [comment]
It's very possible that this was a template that they just copied & pasted here.

When you read through the job description page, it says
> Summer Analysts join us for 10–14 weeks and Co-ops (4 months)
> ...
> You must be studying towards a Bachelor’s or Master’s in Computer Science, Computer Engineering, Electrical Engineering, Mathematics, Physics, Software Engineering or other related technical majors.

which implies that this is an internship and/or co-op.
