### ISSUE TITLE
Honeywell internship visa status

### ISSUE THREAD

**Issue by ysahil97** [pittcsc/Summer2023-Internships#1374]
While searching for internships at Honeywell, I got this paragraph

![image](https://user-images.githubusercontent.com/19690506/195482332-10fdc787-02fb-4429-ac50-22b4544ce947.png)

This may contradict with the no visa sponsorship statement made in Readme for Honeywell.

Could somebody please corroborate this?

**Comment by ewang2002** [comment]
Why do you believe it contradicts the no visa sponsorship statement?

My interpretation is that when the paragraph says (emphasis mine)
> Applicants for employment for this position must have work authorization that **does not now or in the future require** sponsorship of a visa for employment authorization in the United States and with Honeywell

it's essentially saying that you must have prior work authorization; they will not give you work authorization.
