### ISSUE TITLE
The NVIDIA Apply Link Cannot Be Used Anymore

### ISSUE THREAD

**Issue by Mad-LittleRookie** [pittcsc/Summer2023-Internships#1457]
The Link is https://nvidia.wd5.myworkdayjobs.com/en-US/UniversityJobs/job/Interested-in-Internships---Software-2023_JR1961144-1?locationHierarchy1=2fcb99c455831013ea52fb338f2932d8

**Comment by owini** [comment]
Thanks! You can always make a pull request to help update and contribute to the repo!
