### ISSUE TITLE
Additional Conditions on Jet Propulsion Laboratory Internship

### ISSUE THREAD

**Issue by ysahil97** [pittcsc/Summer2023-Internships#1505]
I was going through the NASA JPL page for software internships, it is definitely open.
But the internship expects mostly US citizens or permanent residents. I believe this information should be mentioned in the README.md itself for better initial filtering of the users.
Could anybody please confirm this?

**Comment by ewang2002** [comment]
In the [internship listing we have](https://www.jpl.jobs/job/JJPLUSR2941EXTERNALENUS/Summer-2023-Software-Engineer-Intern),  where does it say that US citizenship is required?

**Comment by ewang2002** [comment]
Oops, forgot to edit my comment before posting.

Yes, I can add a note right now. Or, you can too (you're 100% free to make your own changes and make a pull request).

**Comment by ewang2002** [comment]
Resolved. Next time, feel free to make your own PRs :) Thanks for pointing it out!
