### ISSUE TITLE
Add Rubrik

### ISSUE THREAD

**Issue by arkn98** [pittcsc/Summer2023-Internships#1552]
Software Engineer Intern - Summer 2023 - Palo Alto, CA, USA - https://app.ripplematch.com/job/rubrik/4779bc75/

**Comment by owini** [comment]
Thanks! You can always create a pull request and contribute directly to the repo!

**Comment by owini** [comment]
Updated--thanks!

**Comment by arkn98** [comment]
Sorry, didn't have my laptop with me. Will do it next time.
