### ISSUE TITLE
Closed Internships

### ISSUE THREAD

**Issue by GoodMorningA1i** [pittcsc/Summer2023-Internships#1624]
* Voloridge Investment Management
* KeyBank
* Neocis
* Northrop Grumman
* Lockhead Martin
* PNC
* Yugabyte
* Aquatic Capital Management
* Accenture
* American Express
* Thomson Reuters
* Daikin
* Nasdaq
* Qvest
* Trihydro Corporation
* Ridgeline
* Insitro
* Applied Intuition
* Dell (Nov 18 2022)
* Neuralink
* Zillow
* Deloitte
* LinkedIn
* Discover Financial Services
* VISA
* Chewy
* AIG
* Paramount
* Brex
* Tableau
* Squarespace
* Marvell
* Mailchimp
* Pandora
* Zoom
* Commonwealth

**Comment by owini** [comment]
Will update. Thanks!

**Comment by owini** [comment]
Updated now. Thank you!!
