### ISSUE TITLE
US News may not sponsor

### ISSUE THREAD

**Issue by BrandoZhang** [pittcsc/Summer2023-Internships#1735]
After answering questions related to sponsorship (require H1B in the future), the website says:

```
Thank you for taking the time to complete the online process. Based on the information you provided in the online application, it appears you do not meet the minimum qualifications for this position. Please visit our website to view other openings that better suit your qualifications. Please click FINISH now to complete the online process.
```

**Comment by ewang2002** [comment]
Hm, I don't know if you can do it, but if you try saying that you don't need sponsorship, does it still give that message?

**Comment by BrandoZhang** [comment]
Hi @ewang2002, I tried it with another email address but exactly the same information except for sponsorship, and yes I got into the next page asking me to upload my resume 🥲.

**Comment by ewang2002** [comment]
Interesting. Okay, feel free to make a PR saying that US News might not accept candidates who require sponsorship. Or, I can when I have time.

**Comment by ewang2002** [comment]
Updated the entry!
