### ISSUE TITLE
No Twitter?

### ISSUE THREAD

**Issue by Longday0923** [pittcsc/Summer2023-Internships#1740]
Although I didn't found any intern for 2023 at Twitter...

**Comment by ewang2002** [comment]
Well, considering that Twitter is currently... going through some things, I feel like internships there probably won't be happening.

That being said, if Twitter isn't on the list, it probably means no one found any internship postings on their [website](https://careers.twitter.com/en/roles.html#q=intern&sortBy=relevance). 

If you happen to find any postings (ideally, from their official careers page and not a third-party website), feel free to let us know or -- even better -- make a PR adding the posting to the list.
