### ISSUE TITLE
List of broken links

### ISSUE THREAD

**Issue by arunsathiya** [pittcsc/Summer2023-Internships#1817]
Here's a list of broken links. Some of these appear broken on Powershell but seem to work on the browser, so needs to be verified manually before updating:

- [ ] [500] https://www.deshaw.com/careers/systems-technologist-intern-new-york-4484
- [ ] [404] https://drw.com/work-at-drw/job/quantitative-research-intern-2301002/
- [ ] [404] https://www.riotgames.com/en/j/4526877
- [ ] [404] https://www.riotgames.com/en/j/4526870
- [ ] [404] https://careers.tiktok.com/position?keywords=software
- [ ] [404] https://jobs.bytedance.com/en/position/7138261141784611103/detail?spread=BSPP2KS
- [ ] [500] https://sjobs.brassring.com/TGnewUI/Search/Home/Home?partnerid=25404
- [ ] [302] https://boards.greenhouse.io/relativity/jobs/6363660002?gh_jid=6363660002
- [ ] [404] https://careers.garmin.com/careers-home/jobs/9345?lang=en-us
- [ ] [404] https://careers.garmin.com/careers-home/jobs/9267?lang=en-us
- [ ] [404] https://careers.garmin.com/careers-home/jobs/9266?lang=en-us
- [ ] [404] https://careers.garmin.com/careers-home/jobs/9219?lang=en-us
- [ ] [404] https://careers.garmin.com/careers-home/jobs/9243?lang=en-us
- [ ] [410] https://careers.adobe.com/us/en/job/R131734/2023-Intern-Machine-Learning-Engineer-Intern
- [ ] [403] https://careers.rtx.com/global/en/job/01553158
- [ ] [410] https://www.asml.com/en/careers/find-your-job/5/3/0/software-test-engineer-intern-req53028
- [ ] [410] https://www.asml.com/en/careers/find-your-job/5/2/5/devops-intern-req52528?ppc=JBP-181
- [ ] [404] https://jobs.lever.co/anduril/d15840b6-081b-4d4c-95ed-008d681b4f7f
- [ ] [404] https://jobs.lever.co/anduril/c6d4fc93-2be9-4018-8160-4f490d11328c
- [ ] [404] https://jobs.lever.co/wolve/4a6fd0be-6bb7-4bbb-9dd5-1416d6a5f5b7
- [ ] [403] https://dimensional.wd5.myworkdayjobs.com/en-US/DFA_Campus/job/Austin/Internship-in-Technology---Software-Engineer--Undergraduate---Master-s-_2022-6883
- [ ] [410] https://careers.united.com/us/en/job/WHQ00020911/Intern-Digital-Technology-Summer-2023
- [ ] [404] https://www.weareroku.com/jobs/software-engineer-intern-cloud-san-jose-california-united-states
- [ ] [404] https://www.weareroku.com/jobs/software-engineer-intern-web-san-jose-california-united-states-cabd1cba-0fd6-4dfa-979b-6781a4615cea
- [ ] [404] https://www.weareroku.com/jobs/software-engineer-intern-embedded-san-jose-california-united-states-80f80523-3868-45dd-a784-9177fc95447b
- [ ] [404] https://www.weareroku.com/jobs/software-engineer-intern-machine-learning-san-jose-california-united-states        
- [ ] [410] https://careers-uipath.icims.com/jobs/4797/summer-2023-intern
- [ ] [410] https://careers-uipath.icims.com/jobs/4794/summer-2023-intern
- [ ] [410] https://careers-uipath.icims.com/jobs/4787/summer-2023-intern
- [ ] [410] https://careers.snowflake.com/us/en/job/6397516002?gh_jid=6397516002
- [ ] [404] https://jobs.lever.co/zoox/73ba40c9-48bd-4f34-9eb5-b56d41a74a7d
- [ ] [500] https://tripactions.com/job-openings/4488671?gh_jid=4488671
- [ ] [404] https://careers.ancestry.com/jobs/android-engineer-summer-intern-hybrid-remote-office-based-lehi-utah-united-states
- [ ] [404] https://careers.ancestry.com/jobs/ios-engineer-summer-intern-hybrid-remote-office-based-lehi-utah-united-states   
- [ ] [404] https://careers.ancestry.com/jobs/data-science-cv-nlp-summer-intern-hybrid-remote-office-based-lehi-utah-united-states
- [ ] [403] https://careers.rtx.com/global/en/job/RAYTGLOBAL01567022EXTERNALENGLOBAL/UP-2023-Software-Engineer-Internships    
- [ ] [404] https://jobs.lever.co/vailsys/98edbcac-8756-432e-8aa5-47c36c099b19
- [ ] [404] https://jobs.lever.co/vailsys/39332d76-6599-44af-9481-e7f9162d1ad1/
- [ ] [403] https://www.ziprecruiter.com/c/ZipRecruiter/Job/Data-Scientist-Machine-Learning-Engineer-Intern/-in-Santa-Monica  
- [ ] [403] https://www.ziprecruiter.com/c/ZipRecruiter/Job/Software-Engineer-Intern/-in-Santa-Monica
- [ ] [410] https://careers.carmax.com/us/en/job/JR-102006/Technology-Intern-Richmond-VA-Dallas-TX
- [ ] [410] https://careers.activision.com/job/R017325/Computer-Graphics-Internship
- [ ] [410] https://careers.activision.com/job/R017324/Analytics-Internship
- [ ] [410] https://careers.rbi.com/global/en/job/6262468002/2023-Technical-Development-Program-Summer-Internship-TDP-Software-Engineering-Toronto
- [ ] [404] https://careers.northwesternmutual.com/corporate-careers/job/software-engineering-internship-summer-2023-milwaukee-wi-corporate-jr-35891
- [ ] [404] https://careers.northwesternmutual.com/corporate-careers/job/data-science-analytics-internship-summer-2023-milwaukee-wi-corporate-jr-35887/
- [ ] [410] https://careers-linkindustrialfields.icims.com/jobs/4450/data-analyst-intern-2023/job
- [ ] [410] https://careers-linkindustrialfields.icims.com/jobs/4459/computer-engineering-summer-intern-2023/job
- [ ] [410] https://careers-linkindustrialfields.icims.com/jobs/4602/data-science-intern
- [ ] [404] https://jobs.lever.co/wisk/4d2f1a07-8f6e-4243-ad2d-ebea17e390a9
- [ ] [404] https://www.csdisco.com/careers/software-engineer-intern-c
- [ ] [404] https://www.csdisco.com/careers/software-engineer-intern-6
- [ ] [500] https://phg.tbe.taleo.net/phg03/ats/careers/v2/viewRequisition?org=OMNICELL
- [ ] [404] https://jobs.lever.co/ambirobotics/849d7ae7-67b8-471c-ae1a-ef9beedff270
- [ ] [404] https://jobs.lever.co/ambirobotics/948c66a2-2886-49bf-a9fa-2d1fad7ad678
- [ ] [404] https://jobs.lever.co/ambirobotics/2480fb89-7575-46cb-80d9-3c7a4faaf8f6
- [ ] [404] https://jobs.lever.co/ambirobotics/0051f9b6-c9c4-48fc-a50d-de303e696fe2
- [ ] [404] https://jobs.lever.co/ambirobotics/cfebc000-96e7-4c85-8b9a-47a9b23329c9
- [ ] [404] https://jobs.lever.co/ambirobotics/7e2fb44b-b935-4eec-9f7e-cad8acdd1f1d
- [ ] [404] https://aurora.tech/jobs/software-engineering-intern-back-end-c-6428595002
- [ ] [404] https://aurora.tech/jobs/software-engineering-intern-back-end-python-6427680002
- [ ] [405] https://www.wayfair.com/careers/jobs?countryIds=1
- [ ] [410] https://careers-bluehalo.icims.com/jobs/3603/software-engineering-intern/job
- [ ] [410] https://careers-gdms.icims.com/jobs/57649/job
- [ ] [500] https://jobs.lrs.com/job/details/25154
- [ ] [404] https://boards.greenhouse.io/tusimpleinternship
- [ ] [404] https://jobs.lever.co/color/93e1b4d8-7822-41bc-9d83-f8333cd5230f
- [ ] [404] https://jobs.lever.co/tealium/01b097dc-a904-448d-8cfc-91a372e2156c
- [ ] [404] https://jobs.lever.co/shieldai/f22a791d-d279-4cca-999d-c78aca6c42b0
- [ ] [404] https://jobs.lever.co/shieldai/5a66481a-42c5-447b-8bea-afb9732788c8
- [ ] [404] https://jobs.lever.co/shieldai/b06c8750-7bc9-443b-be21-5213daef44ff
- [ ] [410] https://jobs.baesystems.com/global/en/job/86199BR/Software-Engineering-Intern
- [ ] [410] https://jobs.baesystems.com/global/en/job/86198BR/Systems-Engineering-Intern
- [ ] [410] https://jobs.baesystems.com/global/en/job/86078BR/Virtual-Reality-Engineering-Intern-Summer-2023
- [ ] [410] https://jobs.microfocus.com/global/en/job/7027957/Systems-Software-Engineer-Intern-at-Vertica
- [ ] [410] https://jobs.microfocus.com/global/en/job/7027820/Quality-Assurance-Test-Intern-for-Summer-2023-Vertica
- [ ] [404] https://jobs.lever.co/fanatics/573afdf6-8a23-48a0-8682-b721277f1410
- [ ] [404] https://jobs.lever.co/fanatics/902a3c59-d4ad-46c7-b6ba-277b6ab1bada
- [ ] [404] https://jobs.lever.co/fanatics/2098bd04-743c-4715-b95a-02bed755c69d
- [ ] [404] https://jobs.lever.co/fanatics/94ecad65-b4fc-48b8-ba1b-b3d7c2f8a9c3
- [ ] [410] https://careers.chime.com/job/6451721002/Engineering-Services-Intern
- [ ] [410] https://careers.chime.com/job/6450390002/Risk-Support-Engineering-Intern
- [ ] [410] https://careers.chime.com/job/6451725002/Engineering-Product-Management-Intern
- [ ] [404] https://careers.siriusxm.com/earlycareer/jobs/13805?lang=en-us
- [ ] [404] https://careers.siriusxm.com/earlycareer/jobs/13807?lang=en-us
- [ ] [404] https://careers.siriusxm.com/earlycareer/jobs/13801?lang=en-us
- [ ] [404] https://micron.eightfold.ai/careers/job/13315166?domain=micron.com
- [ ] [404] https://careers.moodys.com/job/16818557/2023-engineering-technology-summer-internship-us-charlotte-nc
- [ ] [403] https://aluperf.referrals.selectminds.com/jobs/search/36227665
- [ ] [403] https://aluperf.referrals.selectminds.com/jobs/machine-learning-and-ai-intern-90993
- [ ] [404] https://boards.greenhouse.io/embed/job_app?token=4472663
- [ ] [403] https://ats.comparably.com/api/v1/gh/integraladscience/jobs/4637063?gh_jid=4637063
- [ ] [404] https://www.pepsicojobs.com/main/jobs/143600?lang=en-us
- [ ] [404] https://enablemedicine.pinpointhq.com/en/jobs/75390
- [ ] [404] https://enablemedicine.pinpointhq.com/en/jobs/75389
- [ ] [404] https://enablemedicine.pinpointhq.com/en/jobs/75391
- [ ] [404] https://enablemedicine.pinpointhq.com/en/jobs/75388
- [ ] [410] https://careers.intuitive.com/us/en/job/JOB2716/Software-Engineer-Intern
- [ ] [410] https://careers.intuitive.com/us/en/job/JOB2747/DevOps-Intern
- [ ] [410] https://careers.intuitive.com/us/en/job/JOB2667/System-Engineer-Intern?utm_source=linkedin
- [ ] [403] https://careers.na.panasonic.com/careers/software-engineering-summer-2023-intern-embedded-software-irvine-ca      
- [ ] [403] https://careers.na.panasonic.com/careers/software-engineering-summer-2023-intern-test-platform-irvine-ca
- [ ] [403] https://careers.na.panasonic.com/careers/software-engineering-summer-intern-device-verification-sw-irvine-ca      
- [ ] [404] https://www.takedajobs.com/job/-/-/1113/41541695120
- [ ] [400] https://www.metacareers.com/jobs/543301834469909/
- [ ] [400] https://www.metacareers.com/v2/jobs/875414340161910/
- [ ] [404] https://www.ga-careers.com/job/boulder/space-software-development-intern/499/41040384016
- [ ] [404] https://www.ga-careers.com/job/herndon/software-engineering-intern/499/40645672416
- [ ] [404] https://jobs.lever.co/spotify/d40b915f-2df6-4f28-822f-34bfaddc4c2b?lever-source=LinkedInJobs
- [ ] [410] https://careers-peraton.icims.com/jobs/130171/summer-2023-cyber-software-engineering-intern--landover
- [ ] [403] https://ats.comparably.com/api/v1/lvr/carbon/02cf6a7e-d13f-47d1-823d-6c4a8bb0f2ed
- [ ] [500] https://phh.tbe.taleo.net/phh03/ats/careers/v2/viewRequisition?org=ELLINGTONMGMTGRP
- [ ] [404] https://recruiting.paylocity.com/Recruiting/Jobs/Details/1554540

**Comment by arunsathiya** [comment]
My friend @sharunkumar generated this actually, and I am posting on his behalf because he is blocked on this repository. Could an admin share why he is blocked?

**Comment by owini** [comment]
Got it! Will look into this and update. Thanks!
