### ISSUE TITLE
Summer 2024 Internships

### ISSUE THREAD

**Issue by ewang2002** [pittcsc/Summer2023-Internships#1838]
I'm surprised that Goldman Sachs already has an internship position for 2024. With that said, perhaps it might be worth separating the table so we have a 2023 and 2024 internship section?

**Comment by owini** [comment]
Sounds great! Yes, financial firms start recruiting early + recently started opening their internships for Summer 2024. Most companies' internship positions will open this summer/early fall.

**Comment by helloaashu** [comment]
I am very much interested in contributing , Would you please provide me with the proper guide..

**Comment by owini** [comment]
Awesome! Here's our contribution guide: https://github.com/pittcsc/Summer2023-Internships/blob/dev/CONTRIBUTING.md

**Comment by antonio-pedro99** [comment]
@owini are these openings only for U.S residents? or it depends?

**Comment by owini** [comment]
Hi, @antonio-pedro99,

It depends on the company and position. Normally sponsorship availability will be included in the job posting or added to the internship repo once recruiting gets underway.
