### ISSUE TITLE
Ramp internship is for Fall, not summer

### ISSUE THREAD

**Issue by satchelmoore** [pittcsc/Summer2023-Internships#1910]
per conversation with a recruiter, the posted Ramp internship is not for summer 2024, but for the fall term.

**Comment by tianyizheng02** [comment]
@satchelmoore By "fall", do you mean Fall 2023?

**Comment by ewang2002** [comment]
Thank you for catching this. I'm going to leave the posting there for now. But, something to consider: @owini has been accepting PRs that add non-summer internships to the README (e.g., #1888, 2e1d460b96032df156dc50a6e44da9d4831e003a, etc.). Perhaps we can create a separate README for off-season internships. What do you all think?

**Comment by owini** [comment]
^second this! Good catch! Let's add the position to the 2023 README and include a note it's for Fall 2023.

**Comment by ewang2002** [comment]
This issue, and the corresponding PR, is getting stale. Going to close both but remove Ramp.
