### ISSUE TITLE
Deadline for Apple AI/ML internship

### ISSUE THREAD

**Issue by hmankodiya** [pittcsc/Summer2023-Internships#1913]
Does anyone know what the deadline [Apple AI/ML Intern](https://jobs.apple.com/en-us/details/200480066/machine-learning-ai-internships) is?

**Comment by ewang2002** [comment]
Key thing to note is
> This posting is not for a specific job opening and by submitting your resume you are expressing interest in being contacted about this type of role at Apple in the future.

So, presumably, this posting is going to stay up at least for a while.

**Comment by tianyizheng02** [comment]
Exactly, and the links in the README say "(Express Interest)" to make it clear that they're only meant to express interest for future postings.
