### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by colmpat** [pittcsc/Summer2023-Internships#1941]
It looks like there is some malformation with the table submission from pr #1940

<img width="1127" alt="Screenshot 2023-06-09 at 8 23 53 AM" src="https://github.com/pittcsc/Summer2024-Internships/assets/69922808/7be9972a-9a7b-4ecb-9482-8864f37b10e1">

**Comment by owini** [comment]
Kk feel free to contribute by creating a PR. thanks!
