### ISSUE TITLE
New Feature Request: Sort by Newest

### ISSUE THREAD

**Issue by andxsu** [pittcsc/Summer2023-Internships#2142]
### Improvement

For applicants that check the repo often for new postings, I think that there should be a sort by Newest option. For me to apply to the newest opening, I have to check the entire repo and crosscheck it with my application list to see if its new. I think the repo is really great and I feel as though this addition could make it better.

**Comment by matttreed** [comment]
Thanks so much for the suggestion andxsu. We went ahead and changed the ordering so the newest postings will always be added to the bottom. The list is now sorted by when the internships were posted!
