### ISSUE TITLE
New Feature Request: Posted Date

### ISSUE THREAD

**Issue by sud298** [pittcsc/Summer2023-Internships#2144]
### Improvement

Add a posted date column, visa sponsorship requirements because as an international student, there is no point of applying to companies that reject the candidates directly for requiring sponsorship.

**Comment by Ruchi-here** [comment]
I guess, it is better to see that ourselves rather than asking for these features because usually it's mentioned in the application form.

**Comment by rushilsrivastava** [comment]
@matttreed is working on adding date posted. Regarding the visa sponsorship status, do you have suggestions on how we should display this data on the table without further complicating the view?

We are adding this data right on Simplify in the next few weeks though, and I think that should hopefully solve your problem.

**Comment by hemanthy1** [comment]
I think having a check box next to the company name would be simple (sponsorship/no sponsorship), however I believe at the very least a strict classification of {US Citizen, Sponsorship, No Sponsorship} in parentheses next to every job opening would be helpful.

**Comment by rudro12356** [comment]
For some reason, the apply buttons for the Simplify column isn't showing. I am not sure if it's a problem on my end. The sponsorship addition would be nice, atleast if a post says US citizen and No sponsorship it would make things really easier for a lot of us. Thank you!

**Comment by matttreed** [comment]
Hey ! Thanks everyone for the feedback. Date Posted is up and running, we're still working on adding sponsorship status, but it should be done shortly.

**Comment by sud298** [comment]
Or we can have another column with tick marks for sponsorship provided and red cross for no sponsorship which has been mentioned explicitly in the JD. Including F1 Stem opt/cpt

**Comment by sud298** [comment]
And is there any repo for new grad roles too?

**Comment by matttreed** [comment]
@sud298 We were thinking something along the same lines (having an emoji to show whether sponsorships are offered or not), but we wanted to avoid adding another column if possible. We're considering adding the emoji to the end of the internship title, but we'll do some UI experiments and see what looks good.
