### ISSUE TITLE
New Feature Request: Add Closed Date

### ISSUE THREAD

**Issue by hemanthy1** [pittcsc/Summer2023-Internships#2146]
### Improvement

In addition to a "date posted", I think a date closed would help for students to gauge the market and make more data freely available to users.

**Comment by rushilsrivastava** [comment]
I like the idea, but it's hard to add all this information the repository while retaining a clear table view. Users who want to see when postings closed can use Git to see the update date, or visit the Simplify posting link. Date posted should be added soon though.
