### ISSUE TITLE
New Feature Request: Sort newest internships at the top

### ISSUE THREAD

**Issue by jeffreymeng** [pittcsc/Summer2023-Internships#2149]
### Improvement

It would be a lot nicer to sort the internships in reverse-chronological order so we don't have to scroll all the way to the bottom to check for new items.

**Comment by yan-michael** [comment]
This is a highly debated topic – we added a "jump to bottom" button so you can easily navigate to the latest postings.

**Comment by jeffreymeng** [comment]
After jumping to the bottom you still have to scroll up to actually see the latest postings, and it just feels like there's more friction this way.

What's the argument for the current ordering?

**Comment by matttreed** [comment]
Yeah as Michael was saying, this has come up a few times between us. We're still considering flipping the order, but decided to stick with the oldest to newest approach that Pitt CSC has been using, at least for the launch. We appreciate the feedback a lot and we'll let you know if we end up switching it!

**Comment by frederickberube0** [comment]
Could you host some kind of vote? I also agree that newest first is ideal. I don't understand why you wouldn't. The old way isn't always the best.

**Comment by sud298** [comment]
Please add it in the reverse chronological order and can you please add something that would show which internships I applied? Because right now I need to keep an excel sheet to do this. Any checkbox which I can tick and remember the companies which I applied to? And can you do a poll for reverse chronological order? For me scrolling has become a real issue in finding the newer ones.

**Comment by matttreed** [comment]
Hey everyone, I just posted a poll about the ordering so feel free to cast your vote

**Comment by matttreed** [comment]
@sud298 As far as adding checkboxes, due to the nature of markdown, these checkboxes would not persist between different visits to the site hence making them useless. You could fork the repository and delete the rows that you've already applied to perhaps?
