### ISSUE TITLE
New Internship: PwC

### ISSUE THREAD

**Issue by hemanthy1** [pittcsc/Summer2023-Internships#2163]
### Link to Internship Posting

https://jobs.us.pwc.com/job/birmingham/nis-cyber-security-and-technology-intern-summer-2024/932/52142558336

### Company Name

PwC

### Internship Title

Cyber Security and Technology Intern

### Location

Birmingham, AL | Fayetteville, AR | Little Rock, AR | Phoenix, AZ | Irvine, CA | Los Angeles, CA | Sacramento, CA | San Diego, CA |  San Francisco, CA | Silicon Valley, CA | Denver, CO | Hartford, CT | Stamford, CT | Washington, DC | Hallandale Beach/Miami, FL | Jacksonville, FL | Orlando, FL | Tampa, FL | West Palm Beach, FL | Atlanta, GA | Des Moines, IA | Chicago, IL | Indianapolis, IN | Louisville, KY | New Orleans, LA | Boston, MA | Baltimore, MD | Detroit, MI | Grand Rapids, MI | Minneapolis, MN | Kansas City, MO | St. Louis, MO | Charlotte, NC | Greensboro, NC | Raleigh, NC | Florham Park, NJ | Las Vegas, NV | Albany, NY | Buffalo, NY | Melville, NY | New York, NY | Rochester, NY | Cincinnati, OH | Cleveland, OH | Columbus, OH | Toledo, OH | Oklahoma City, OK | Tulsa, OK | Portland, OR | Philadelphia, PA | Pittsburgh, PA | Columbia, SC | Spartanburg, SC | Nashville, TN | Austin, TX | Dallas, TX | Fort Worth, TX | Houston, TX | San Antonio, TX | Remote, US | Salt Lake City, UT | Richmond, VA | Montpelier, VT | Seattle, WA | Milwaukee,  WI

### What term(s) is this internship offered for?

Summer 2024

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

Included all locations separated by pipe (might be too long tho)

### Email associated with your GitHub account (Optional)

hemanthy@gmail.com

**Comment by matttreed** [comment]
wow im impressed by the number of pipes here haha! thanks for all your contributions hemanthy <3
