### ISSUE TITLE
Scraping Tool

### ISSUE THREAD

**Issue by hemanthy1** [pittcsc/Summer2023-Internships#2164]
### Tell us what's up?

As this repo is becoming more streamlined and helps more students achieve their goals, I would love to be at the forefront. I am not familiar with how internships are updated on Simplify and get ported to the repo, but I believe a simple scraping tool would be incredibly helpful. I am more than willing to spend some of my time working on it as well (if it's something the owners believe would be helpful too).

**Comment by nickorlow** [comment]
https://olney.nickorlow.com/jobs

This is a scraper I wrote, updates every minute. It parses it to JSON. Needs an update to fix parsing multiple locations & sponsorship info.

**Comment by hwuiwon** [comment]
@nickorlow I personally think that updating every 10 minute will be also fine. Feel like every minute is bit of an overkill

**Comment by nickorlow** [comment]
> @nickorlow I personally think that updating every 10 minute will be also fine. Feel like every minute is bit of an overkill

Probably. Would eventually like to send out push notifs so you can be alerted right when a new posting goes live which is why it's one minute. 

I'm planning on open sourcing this, it'll be configurable to end-users when I do so.

**Comment by matttreed** [comment]
@hemanthy1 I'm guessing you meant a scraper to add new internships to the repo? That would be pretty sick.

**Comment by matttreed** [comment]
@nickorlow I'm impressed by the scraper you managed to make haha. I hate to rain on your parade but all the data (and more) is already stored in a json file [here](https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/.github/scripts/listings.json). All changes to the repo are made through that file which spawns a github action that regenerates each `README`. It's dope that you're making open-source projects with it! Excited to see what you make.
