### ISSUE TITLE
New Feature Request:  Require all locations be listed when number of locations is low

### ISSUE THREAD

**Issue by nickorlow** [pittcsc/Summer2023-Internships#2171]
### Improvement

Some internships don't list all locations, instead opting to have their location set to something like:

Multiple US Locations

Plano, TX and 2 other locations

I think that in the event that there's not a lot of locations (<= 5 locations?) that it might be best to require that that all locations be listed. If there's more than 5, then I think something like "64 US Locations, 2 Canadian Locations" or "66 Worldwide Locations" would be best.

**Comment by matttreed** [comment]
Hey @nickorlow, thanks for your suggestion! As of now, the list does show all locations up to three for internships. I just added dropdowns for listings with more than 3 locations, so hopefully, that's pretty intuitive to use. The reason that some of them say "Multiple" or "Multiple US Locations" is that these are listings from the old Pitt CSC repo that didn't have any sort of designated format for locations.
