### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by RaiJashan17** [pittcsc/Summer2023-Internships#2172]
### Link to Internship Posting

https://www.lockheedmartinjobs.com/job/orlando/software-engineering-intern/694/52455467776

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Edited the link, original link leads to an error. This link above currently works.

### Email associated with your GitHub account (Optional)

raijashan17@gmail.com

**Comment by matttreed** [comment]
Thanks for the update <3
