### ISSUE TITLE
Crowdstrike Link

### ISSUE THREAD

**Issue by ajain02** [pittcsc/Summer2023-Internships#2183]
Crowdstrike link lands on careers page and pretty much every link on their website links back to their general careers page. Please paste the real position!

**Comment by matttreed** [comment]
Hey @ajain02 thanks for submitting an issue. I'm not sure what you're talking about in particular. Would you mind being more specific or posting the "real" link so I can see what you mean

**Comment by yan-michael** [comment]
@ajain02 Can't replicate your issue – make sure you're clicking the "Apply" button :)
