### ISSUE TITLE
Some job listing links do not like the additional params that the repo ends up adding in

### ISSUE THREAD

**Issue by andylin2004** [pittcsc/Summer2023-Internships#2188]
### Tell us what's up?

Some job listing links do not like the additional params that the repo ends up adding in--Amazon seems to be a big one for me

(By additional params I mean the utm_source=SimplifyGH&ref=Simplify part of the original URL)

**Comment by matttreed** [comment]
Hey @andylin2004 , thanks for letting us know. I haven't run into this issue myself, so would you mind elaborating on what happens when you click the link?

**Comment by andylin2004** [comment]
For Amazon: the job listing page loads as normal. But when I click on the apply job button and log into my Amazon jobs account, I get sent to a page showing what applications I have submitted instead of a form to fill out

**Comment by rushilsrivastava** [comment]
This is the normal behavior on Amazon (and also most sites without a callback url).
