### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by utkarshsingh99** [pittcsc/Summer2023-Internships#2204]
### Link to Internship Posting

https://www.vanguardjobs.com/job-search-results/?level[]=Student%20%26%20Recent%20Graduates

### Company Name

Vanguard

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

The current link is not valid.

**Comment by matttreed** [comment]
hey @utkarshsingh99 ! thanks for submitting this issue! This was actually due to a bug in our script that handles URL query parameters, so thanks for bringing this to light! It should be fixed now
