### ISSUE TITLE
New Feature Request: Please add Internships related to Cloud, DevOps and SRE

### ISSUE THREAD

**Issue by ghost** [pittcsc/Summer2023-Internships#2208]
### Improvement

Hey Team,

Thanks for doing an amazing job of keeping us updated about all the internship openings. 

A small request to keep us posted about any new openings in devops/cloud/sre, It would really help people like me who are interested in these domains, They are really tough to find as well.

Thanks for taking some time to read this.

**Comment by cwcoogan** [comment]
If this is integrated can we separate this into another repository separate from SWE as the list is already growing rapidly? The easy solution is using filters, but I am unsure that Github allows that. Happy to help build this out if needed.
