### ISSUE TITLE
Capital One - Custom Job Error

### ISSUE THREAD

**Issue by PranavMishra28** [pittcsc/Summer2023-Internships#2211]
### Issue/Question

Capital One's Internship link gives a Custom Job Error: https://www.capitalonecareers.com/job/mclean/product-development-intern-summer-2024/31238/51746418592?utm_source=Simplify-GH&ref=Simplify

**Comment by nilsreichardt** [comment]
![image](https://github.com/SimplifyJobs/Summer2024-Internships/assets/24459435/6820f1b4-e9a0-4383-8765-ee8a5860fc43)

Is location access required?

**Comment by rushilsrivastava** [comment]
This job is already closed and not listed on the repo
