### ISSUE TITLE
Taboola internship expired 

### ISSUE THREAD

**Issue by marmikpatel19** [pittcsc/Summer2023-Internships#2214]
### Link to Internship Posting

https://simplify.jobs/c/Taboola

### Company Name

Taboola

### Internship Title

Backend Engineer Intern

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [X] Yes, remove this internship

**Comment by rushilsrivastava** [comment]
This has been updated already, thanks for your contribution!
