### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by jasonroy7dct** [pittcsc/Summer2023-Internships#2238]
### Link to Internship Posting

https://eyglobal.yello.co/external/requisitions/ojTkvyBtNK5i6AmPxcfdgA

### Company Name

EY

### Internship Title

Summer Associate - Software Strategy Group (SSG) 

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

**Comment by matttreed** [comment]
I can't seem to find this internship in the list. is it already on the repo?

**Comment by jasonroy7dct** [comment]
I want to add a new internship to this list

**Comment by matttreed** [comment]
Oh haha, cool then submit a "New Internship" issue form instead of an "Edit Internship"
