### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by andylin2004** [pittcsc/Summer2023-Internships#2249]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/3676847954/

### Company Name

Whereabouts.ai

### Internship Title

Geospatial Software Development Intern

### Location

Seattle, Washington, United States (Preferred) | Phoenix, Arizona, United States (Preferred) | San Francisco Bay area, California | United States Remote, United States

### What term(s) is this internship offered for?

Fall 2023

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

andylin@nyu.edu

### Extra Notes (Optional)

Applicant must be pursuing a masters or above in CS or related field

**Comment by hemanthy1** [comment]
Not Summer 2024, in the application they say they require the position to be filled “immediately”

**Comment by rushilsrivastava** [comment]
> Not Summer 2024, in the application they say they require the position to be filled “immediately”

Weird description, but it looks fine to add to off-season.
