### ISSUE TITLE
Disco does not sponsor

### ISSUE THREAD

**Issue by marmikpatel19** [pittcsc/Summer2023-Internships#2252]
### Link to Internship Posting

https://www.csdisco.com/careers-listing?gh_jid=6885075002&utm_source=SimplifyGH&ref=Simplify

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Both recent Disco positions do not offer sponsorship: "Applicants must be authorized to work for ANY employer in the U.S. We are unable to sponsor or take over sponsorship of an employment Visa at this time."

**Comment by rushilsrivastava** [comment]
Hi, thank you for your contribution. I have updated the correct link in your issue template, please make sure to link the job, not company page. Thanks!
