### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by trihoang0809** [pittcsc/Summer2023-Internships#2255]
### Link to Internship Posting

https://jobs.aligntech.com/jobs/36257?iis=Job+Board&iisn=LinkedIn&lang=en-us&utm_source=SimplifyGH&ref=Simplify

### Company Name

JBS USA

### Internship Title

Information Technology Intern

### Location

Greeley, CO

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

trihoang0809@gmail.com

### Reason for edit

Job has been filled. There is also a similar one above.

**Comment by rushilsrivastava** [comment]
This posting looks open? I might be missing something here.
