### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by trihoang0809** [pittcsc/Summer2023-Internships#2282]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/job/1590499/Software-Engineering%3A-Intern-Opportunities-for-University-Students%2C-Redmond

### Company Name

Microsoft

### Internship Title

Software Engineer Intern

### Location

Redmond, WA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

trihoang0809@gmail.com

**Comment by hemanthy1** [comment]
I think this is a copy of #2279

**Comment by rushilsrivastava** [comment]
Closing in favor of #2279

**Comment by nguyenvothuan** [comment]
Nice catch, lgtm
*Vo Thuan Nguyen*
Student

High School For The Gifted - VNU
153 Nguyen Chi Thanh, District 5, HCM City
t: 0907-501-946
e: ***@***.***
[image: Facebook icon] <https://www.facebook.com/CodeTwo>   [image:
LinkedIn icon] <https://www.linkedin.com/company/codetwo>   [image: Twitter
icon] <https://twitter.com/CodeTwoSoftware>   [image: Google Plus icon]
<https://plus.google.com/+CodeTwoSoftware>   [image: Youtbue icon]
<https://www.youtube.com/user/CodeTwoChannel>
