### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by sud298** [pittcsc/Summer2023-Internships#2283]
### Link to Internship Posting

https://simplify.jobs/c/FetchRewards

### Company Name

Fetch

### Internship Title

Backend Engineering – Apprenticeship

### Location

Chicago, IL

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Closed.

**Comment by rushilsrivastava** [comment]
Thank you for the contribution. This internship has been autoclosed!
