### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by abhiishek340** [pittcsc/Summer2023-Internships#2284]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/job/1590499/Software-Engineering%3A-Intern-Opportunities-for-University-Students%2C-Redmond

### Company Name

Microsoft

### Internship Title

Software Engineering

### Location

Redmond

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

abhiishek340@gmail.com

**Comment by andylin2004** [comment]
Copy of #2279

**Comment by rushilsrivastava** [comment]
Closing in favor of #2279
