### ISSUE TITLE
New Feature Request: new grad positions

### ISSUE THREAD

**Issue by jay-joo-code** [pittcsc/Summer2023-Internships#2294]
### Improvement

Would it be possible to link to new grad roles along with the internship roles? 
Or have a separate new grad positions list. 
Thanks!

**Comment by rushilsrivastava** [comment]
Hey! We plan on launching a new grad repo soon. In the meantime, we are already have plenty of [new grad roles on Simplify](https://simplify.jobs/jobs?experience=Entry%20Level%2FNew%20Grad&category=Software%20Engineering)

**Comment by matttreed** [comment]
hey @jay-joo-code ! We finally launched [2024-New-Grad-Tech-Roles](https://github.com/SimplifyJobs/2024-New-Grad-Tech-Roles). It works exactly the same as this repo, except with full time entry-level positions instead of internships
