### ISSUE TITLE
New Feature Request: ios / android extension or app

### ISSUE THREAD

**Issue by sud298** [pittcsc/Summer2023-Internships#2322]
### Improvement

Guys I appreciate the extension in chrome but is there any mobile is version for iOS and Android? I cannot open my pc every time and then apply for auto fill. Can you please help me out there? 

Thanks

**Comment by rushilsrivastava** [comment]
Hey! Please feel free to email our team at support@simplify.jobs for questions regarding Simplify. The issues should be exclusively used for the internship repository.

If you are on iOS, you can use the Orion Browser and on Android, you can use Kiwi or Firefox. We have plans for native apps soon.
