### ISSUE TITLE
Small improvement: Legend & Hyperlink

### ISSUE THREAD

**Issue by walkerselby** [pittcsc/Summer2023-Internships#2345]
### Issue/Question

I (and a few friends) missed the legend the first time I viewed the list. Adding "Legend" in h3 above the legend itself could make this more visible.

For example: 
### Legend
 - 🛂 - Does NOT offer Sponsorship
 - 🇺🇸 - Requires U.S. Citizenship
 - 🔒 - Internship application is closed

```
## The List 🚴🏔
### Legend
 - 🛂 - Does NOT offer Sponsorship
 - 🇺🇸 - Requires U.S. Citizenship
 - 🔒 - Internship application is closed
``` 

It could also be hyperlinked in the updates section in the meantime. 
` > - Sponsorship Information is now shown using emojis [(see legend)](#legend) `

**Comment by chiragbhansali** [comment]
Probably it's an overkill but the emojis next to internships could be linked to the legend.

**Comment by matttreed** [comment]
hey @walkerselby ! Great idea. I added the title to make it clearer. The update section has been replaced so I couldn't hyperlink, but that was also a fire idea
