### ISSUE TITLE
Edit Requirement of the Internship

### ISSUE THREAD

**Issue by dhruvac29** [pittcsc/Summer2023-Internships#2414]
### Link to Internship Posting

https://www.ursamajor.com/careers/4309511005?gh_jid=4309511005&utm_source=Simplify&ref=Simplify

### Company Name

Ursa Major

### Internship Title

2024 Summer Avionics Software Engineer Internship

### Location

Loveland, CO

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

This Internship requires US Citizenship and you forget to put a flag with a role that shows specific requirements.

**Comment by hemanthy1** [comment]
Another person just pointed this out, thank you though!
