### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by seany4ng** [pittcsc/Summer2023-Internships#2452]
### Link to Internship Posting

https://boards.greenhouse.io/benchling/jobs/5325466

### Company Name

Benchling

### Internship Title

Software Engineer Intern (Summer 2024)

### Location

San Francisco, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

Yes

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

seanyang12345@gmail.com

**Comment by cwcoogan** [comment]
Is this a "new internship"? if so. Please re-submit this issue with the co
