### ISSUE TITLE
Update Oracle internships

### ISSUE THREAD

**Issue by marmikpatel19** [pittcsc/Summer2023-Internships#2453]
### Link to Internship Posting

Multiple

### Company Name

Oracle 

### Internship Title

Software Engineer Intern

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

All the Oracle internships require students to reside in the US and obtain work authorization for 2024 summer. A note should be made about this as it's similar to an internship not providing sponsorship.

**Comment by cwcoogan** [comment]
I will look into this, but I believe this is the same as using CPT. Using CPT does not require companies to sponsor as it is on the students University to do so.

**Comment by marmikpatel19** [comment]
What is CPT? How does that work?
