### ISSUE TITLE
Non-tech internships being listed? <issue>

### ISSUE THREAD

**Issue by keatonmartin** [pittcsc/Summer2023-Internships#2488]
### Issue/Question

Hey, was just curious why a non-tech internship is listed? In particular, "Editorial Intern" at "Jerry" is just a marketing role with really no relation to tech. That seems to have been a role manually added by a staff member of Simplify as well. 

If the scope of the list has been expanded since Simplify acquired this repo then so be it, but it should probably be reflected in the preamble to the list.

**Comment by cwcoogan** [comment]
Hi. Thank you for your response. There are multiple ways new internships are being posted.. that being from the open source community & from Simplify's database. The main focus of this repository is software engineering/DS/PM. The repository has not been expanded. We are working on reducing the noise of outside internships being added.
