### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by DaviZCodes** [pittcsc/Summer2023-Internships#2499]
### Link to Internship Posting

https://jobs.smartrecruiters.com/Visa/743999927641590?utm_source=Simplify&ref=Simplify

### Company Name

VISA

### Internship Title

Software Engineer – Intern - Summer 2024 (ALL OTHER VISA INTERNSHIPS TOO)

### Location

All

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

No sponsorship. Permanent Authorization to work in the U.S. is a precondition.

### Is this internship currently accepting applications?

Yes

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

All of the VISA internships **do not offer sponsorship**. Make sure to add the 🛂, so people do not get confused and waste their time.

**Comment by pratikshah11** [comment]
They've mentioned the pay for US applicants. It doesn't mean that the applicants can only be US citizens. They are just telling the salary range for applicants applying in US.

**Comment by hemanthy1** [comment]
The VISA applications state that they will not provide sponsorship however they do not require US Citizenship.

**Comment by DaviZCodes** [comment]
> They've mentioned the pay for US applicants. It doesn't mean that the applicants can only be US citizens. They are just telling the salary range for applicants applying in US.

Yeah, but only people with permanent work authorization can apply though. 
I edited the issue.
