### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nerdanar** [pittcsc/Summer2023-Internships#2503]
### Issue/Question

Hello,
This is a fantastic source for the job-searchers. I have a suggestion for this.
I am an Indian student and am currently searching for an internship. If I cannot find one, my scholarship will be snatched away, and I won't be able to pay my college fees. I have been applying for jobs, but as no job is in India, I don't have any visa to the US, etc. I am not authorized to work there.
As there are many contributors to this GitHub repo, please include some contributors from India to benefit a student like me to get a job. Also, You can maintain the GitHub repo Nation-Wise. That will be easier for the job searchers to navigate through the jobs in their country or country of their desire.

This Github repo can be a great source globally if the jobs listed here are wider than one region.

Thanks

**Comment by rushilsrivastava** [comment]
While I am not sure of what resources are available for students in India, we've made a conscious decision to limit the scope of this repo to the US, Canada and UK to make it more streamlined.
