### ISSUE TITLE
visa does not sponsor

### ISSUE THREAD

**Issue by marmikpatel19** [pittcsc/Summer2023-Internships#2507]
### Link to Internship Posting

Multiple

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

"Work Authorization: Permanent Authorization to work in the U.S. is a precondition of employment for this position. Visa will not sponsor applicants for work visas in connection with this position. Future sponsorship will not be considered."

**Comment by cwcoogan** [comment]
Please create individual edit internship issues for each listing with their individual urls. Thank you!
