### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by brandonszeto** [pittcsc/Summer2023-Internships#2523]
### Link to Internship Posting

https://jobs.aligntech.com/jobs/36802?lang=en-us&previousLocale=en-US

### Company Name

Align Technology

### Internship Title

Engineering & Technology Internship

### Location

Multiple Locations

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

brandonszeto@gmail.com

### Reason for edit

The current link to the expression of interest (2024) is no longer working. The link above works.

**Comment by cwcoogan** [comment]
Thank you. I will manually update this as our system only allows us to change links via PRs. Thank you.
