### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by yihui-hu** [pittcsc/Summer2023-Internships#2545]
### Link to Internship Posting

https://asana.com/jobs/apply/5175392?gh_jid=5175392&gh_src=Simplify

### Company Name

Asana

### Internship Title

Software Engineering Intern

### Location

SF

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

yihui.hu@tufts.edu

**Comment by hemanthy1** [comment]
This already exists
