### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by sananov** [pittcsc/Summer2023-Internships#2550]
### Link to Internship Posting

https://fetchnotifs.com/careers?utm_source=Simplify&ref=Simplify

### Company Name

FetchNotifs

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

No longer accepting applications

**Comment by hemanthy1** [comment]
Can you please edit this with the exact url from the repository

**Comment by sananov** [comment]
https://fetchnotifs.com/careers?utm_source=Simplify&ref=Simplify
