### ISSUE TITLE
Solutions Analyst - Intern

### ISSUE THREAD

**Issue by Mario750614** [pittcsc/Summer2023-Internships#2584]
### Link to Internship Posting

https://careers.fedex.com/intern/jobs/RC659654?lang=en-us&previousLocale=en-US

### Company Name

FedEx

### Internship Title

Intern I Solutions Analyst

### Location

Memphis, TN

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kbbk0111@att.net

**Comment by cwcoogan** [comment]
Does not fit the repositroy. "Under close supervision, the successful candidate will assist with the planning and execution of Corporate Sales initiatives. " This repostitory is NOT for sales/enablement/operations. It is for Software Engineering & closely related positions (DS/ML/AI)

**Comment by Mario750614** [comment]
all these intern jobs are tech intern jobs, just what your repo asked for:  Use this repo to share and keep track of software, tech, CS, PM, quant internships for Summer 2024.

**Comment by tt226** [comment]
Unsubscribe
