### ISSUE TITLE
Solutions Specialist Intern

### ISSUE THREAD

**Issue by Mario750614** [pittcsc/Summer2023-Internships#2585]
### Link to Internship Posting

https://careers.fedex.com/intern/jobs/RC659648?lang=en-us&previousLocale=en-US

### Company Name

FedEx

### Internship Title

Solutions Specialist Intern

### Location

Memphis, TN

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kbbk0111@att.net

**Comment by cwcoogan** [comment]
Please review the documentation and purpose of this repository. This does not meet the repositories focus.
