### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by henryxu0** [pittcsc/Summer2023-Internships#2596]
### Link to Internship Posting

https://careers.humana.com/job/19065118/humana-2024-it-summer-internship-remote/

### Company Name

Humana

### Internship Title

Tech Internship Program

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

The application link has reopened to the Humana 2024 Summer tech internship program, I am providing the new link here to be posted.

**Comment by hemanthy1** [comment]
It seems you can’t necessarily re open closed openings. However, can you please create a “new internship” issue with the new link instead please?
