### ISSUE TITLE
Associate Product Manager Intern, Summer 2024

### ISSUE THREAD

**Issue by t-iuy987** [pittcsc/Summer2023-Internships#2611]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/76457290250494662-associate-product-manager-intern-summer-2024?src=Online%2FGoogle%20Website%2FByF&utm_source=Online%20&utm_medium=careers_site%20&utm_campaign=ByF&distance=50&employment_type=INTERN&company=GFiber&company=Wing&company=Waymo&company=X&company=Fitbit&company=Google&company=YouTube

### Company Name

Google

### Internship Title

Associate Product Manager Intern

### Location

San Bruno, CA, USA | San Francisco, CA, USA | Mountain View, CA, USA | New York, NY, USA.

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

No

### Email associated with your GitHub account (Optional)

urvahm01@gmail.com

### Extra Notes (Optional)

This role will begin accepting applications on **September 18, 2023.** _The application deadline is by September 25, 2023._

**Comment by brandon-nguyen-lam** [comment]
Thanks! Since this isn't open until September 18th, I'm gonna wait a week before adding to the repo to avoid confusion.
