### ISSUE TITLE
New Feature Request: A New Column for General Category of Role and Addition Column named "Description"

### ISSUE THREAD

**Issue by CoderJeffrey** [pittcsc/Summer2023-Internships#2643]
### Improvement

Current Internship Posting Display of Role is ambiguous 

For example: for the same "software engineer intern" position
1. Software Engineer Intern
2. Intern – Software Developer - Summer 2024
3. Software Engineer Intern - Applications/CE team

<img width="856" alt="image" src="https://github.com/SimplifyJobs/Summer2024-Internships/assets/60024073/4ee561fe-46b7-4ff7-bd93-b50ca259633c">

Indeed, different expressions provide a better context for the posting but it is not straightforward.
I am proposing the following way to make the posting information more straightfforward:

Take an example of: Software Engineer Intern - Applications/CE team
1. Add a different column named Description
Includes information: "Applications/CE team"

2. For Role Column
Only leave "Software Engineer Intern"

Take another example of "Software Development Engineer in Test Intern - Summer 2024"
1. Add a different column named Description
Includes information: "Software Development Engineer in Test Intern - Summer 2024"

2. For Role Column
Only leave "Software Engineer Intern"

Another example of "2024 Summer Intern: Walmart Connect – Walmart Intern - Data Science"
1. Add a different column named "Description"
Includes information: "2024 Summer Intern: Walmart Connect – Walmart Intern - Data Science"

2. For Role Column
Only leave "Data Analyst Intern"

Besides, for roles, I am proposing the following categories:
["Software Engineer Intern", "Data Analyst Intern", "Quantitative Research Inter", "Quantitative Trading Intern", "Business Intelligence Intern", "Machine Learning Intern", "Research Intern"]

Feel free to add more general categories.
I think by this revision, this repository can be More straightforward, saving time for job seekers!

**Comment by rushilsrivastava** [comment]
Hi, this is possible on [Simplify](https://simplify.jobs/), and we'll be launching a new list that will make this easier to visualize. Unfortunately, because of the limitations of GitHub and Markdown, this is not achievable in a way that maintains the readability of the repo.

**Comment by rushilsrivastava** [comment]
In lieu of #2726, I am going to reopen this issue and allow others to share their thoughts
