### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by sud298** [pittcsc/Summer2023-Internships#2654]
### Link to Internship Posting

Garda Capital Partners

### Company Name

Garda

### Internship Title

Trading Intern

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Remove irrelevant internship

**Comment by cwcoogan** [comment]
Please edit this issue and refer to Contributing.md. You need to include the link to the internship, and you need to check the box to remove it.
