### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by lizebear** [pittcsc/Summer2023-Internships#2728]
### Link to Internship Posting

https://boards.greenhouse.io/8451university/jobs/6867212002

### Company Name

84.51°

### Internship Title

Engineering Intern

### Location

Chicago, IL | Cincinnati, OH

### What term(s) is this internship offered for?

Spring 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

This is the Data Science/Tech Arm of Kroger - 2nd largest grocery in US behind Walmart. Internship can be software dev or data eng

**Comment by cwcoogan** [comment]
please edit the title to software engineer intern
