### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by cobalt1164** [pittcsc/Summer2023-Internships#2775]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/job/1590522/Explore-Program%3A-Internship-Opportunities-for-Second-Year-University-Students

### Company Name

Microsoft

### Internship Title

Software Engineering Intern - Explore Program

### Location

Redmond, WA | Mountain View, CA | Atlanta, GA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bui40277@gmail.com

**Comment by haseeb00110** [comment]
I applied to this internship 2 months ago, now it's in the inactive section and the status shows "Transferred".
