### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by rohitgandhari** [pittcsc/Summer2023-Internships#2777]
### Link to Internship Posting

https://boards.greenhouse.io/springhealth66/jobs/4315743005?gh_src=a8d055a25us

### Company Name

Spring Health

### Internship Title

Software Engineer Intern

### Location

Remote

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

rohy.gandhari@gmail.com

**Comment by pratikshah11** [comment]
This internship is already posted
