### ISSUE TITLE
<issue> URGENT SECURITY ISSUE

### ISSUE THREAD

**Issue by SharpPig** [pittcsc/Summer2023-Internships#2779]
### Issue/Question

Recent home depot internship leads to a fake site that asks for a users SSN when signing up. This is not the same as the real home depot site, it is a clone.

**Comment by hemanthy1** [comment]
I clicked apply and it went to a proper portal. In addition, the domain is homedepot.com which is owned by homedepot. Can you please post a screen recording or screenshot of what you receive and the steps to reproduce it?

**Comment by KathyJDev** [comment]
Although it might seem strange, Home Depot does actually ask for the last 4 digits of the applicant's social security number for identity verification. 

Other applicants have experienced this requirement here:
https://www.indeed.com/cmp/The-Home-Depot/faq/do-home-depot-ask-for-ssn-in-application?quid=1dp981l0o5j53800
