### ISSUE TITLE
<issue> Duplicate Internship Opportunities

### ISSUE THREAD

**Issue by DooHwanKim0419** [pittcsc/Summer2023-Internships#2780]
### Issue/Question

I appreciate the effort put into curating and posting internship opportunities. However, I've noticed that there seems to be a significant number of duplicate listings. While I'm grateful for the support and resources available to us, it might be beneficial to consider checking if the role is already posted here when reviewing the pull request to reduce redundancy. This would streamline the search process for applicants like me and ensure that our time is spent more efficiently exploring unique and valuable internship options!

**Comment by ColeBandz** [comment]
great, let there be a secured web link to the listed Internship opportunity

**Comment by cwcoogan** [comment]
Thanks for the feedback. There are several moderators of whom are checking and removing duplicate posts constantly. We ask that if you see any duplicates we over-missed to submit an issue. Thank you
