### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by Marwanyx** [pittcsc/Summer2023-Internships#2782]
### Link to Internship Posting

https://www.grammarly.com/jobs/engineering/software-engineering-intern?gh_jid=5396077

### Company Name

Grammarly

### Internship Title

Software Engineering Intern

### Location

United States | Canada

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by hemanthy1** [comment]
I think there may be an issue with one of the columns being improperly edited, can you submit another issue please?
