### ISSUE TITLE
Software Engineer Intern (Summer 2024)

### ISSUE THREAD

**Issue by luisbarajasr** [pittcsc/Summer2023-Internships#2958]
### Link to Internship Posting

https://jobs.netflix.com/jobs/298350570

### Company Name

Netflix

### Internship Title

Software Engineer Intern

### Location

Los Gatos, California

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by hemanthy1** [comment]
Already included
