### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by MonishSoundarRaj** [pittcsc/Summer2023-Internships#2983]
### Link to Internship Posting

https://careers.adobe.com/us/en/job/R141264/2024-Intern-Software-Development-Engineer

### Company Name

Adobe

### Internship Title

2024 Intern - Software Development Enginer

### Location

San Jose, California, US

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

msoundar@uncc.edu

**Comment by brandon-nguyen-lam** [comment]
on list
