### ISSUE TITLE
New Internship with Marriott International

### ISSUE THREAD

**Issue by SteveFeldman** [pittcsc/Summer2023-Internships#2990]
### Link to Internship Posting

https://ejwl.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/23165751/?keyword=HQ+Fellow%252FIntern&mode=location

### Company Name

Marriott International

### Internship Title

Fellowship Internship in Technology

### Location

Washington ,DC

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by brandon-nguyen-lam** [comment]
too ambiguous
