### ISSUE TITLE
Autodesk - Technical Program Manager Intern

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3030]
### Link to Internship Posting

https://autodesk.wd1.myworkdayjobs.com/Ext/job/California-USA---Remote/Intern--Technical-Program-Manager--Summer-2024-_23WD72391-1

### Company Name

Autodesk

### Internship Title

Technical Program Manager Intern

### Location

California, CA | Remote

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by brandon-nguyen-lam** [comment]
already in list
