### ISSUE TITLE
Autodesk - Security Engineer Intern

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3031]
### Link to Internship Posting

https://autodesk.wd1.myworkdayjobs.com/Ext/job/California-USA---Remote/Intern--Security-Engineer--Summer-2024-_23WD73082-1

### Company Name

Autodesk

### Internship Title

Security Engineer Intern

### Location

California, CA | Remote

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by brandon-nguyen-lam** [comment]
listing gone
