### ISSUE TITLE
The Cigna Group Internship Closed

### ISSUE THREAD

**Issue by PresidentSam100** [pittcsc/Summer2023-Internships#3075]
### Link to Internship Posting

https://jobs.thecignagroup.com/us/en/job/CIGNUS23015032EXTERNALENUS/Technology-Development-Program-TECDP-Summer-Intern-2024-Evernorth?utm_source=Simplify&ref=Simplify

### Company Name

The Cigna Group

### Internship Title

Technology Development Program (TECDP) Summer Internship

### Location

Bloomfield, CT | Austin, TX | Bloomington, MN | Denver, CO | Morris Plains, NJ | Nashville, TN Philadelphia, PA | St. Louis, MO

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

pbcmarsh@gmail.com

### Reason for edit

Internship closed

**Comment by PresidentSam100** [comment]
Huh, could you be a bit more specific on the error if any?

**Comment by PresidentSam100** [comment]
Additionally, for most (if not all) of the internships in which I made an Issue saying they were closed, I still see the "Apply" button rather than the lock 🔒symbol for those. Will these be updated, or do I have to update them? Thanks!

**Comment by hemanthy1** [comment]
> Huh, could you be a bit more specific on the error if any?

Sorry, that's an error that occurs when too many contributions get accepted at once.
