### ISSUE TITLE
New Feature Request: Close Internship

### ISSUE THREAD

**Issue by PresidentSam100** [pittcsc/Summer2023-Internships#3083]
### Improvement

I'm noticing a lot of times when I (and many others) use "Edit Internship", we are simply closing an internship. I think having this feature would be very effective since instead of having to fill out a lot of unnecessary information (e.g. Location, Offers Sponsorship, terms of internship, the reason for edit) repeatedly, we can the part in the README or the Company and Position which can save lots of us time.

**Comment by hemanthy1** [comment]
You should not have to fill in all the information when closing an internship. The only thing required is the url and "Is this internship currently accepting applications". The other sections are optional and don't have to be filled if you are not editing those.

**Comment by PresidentSam100** [comment]
Ok thank you, that's all I need to know.
