### ISSUE TITLE
Maintaining an Airtable for this repo

### ISSUE THREAD

**Issue by aakash1104** [pittcsc/Summer2023-Internships#309]
Have you thought about using [Airtable](https://airtable.com/) instead of Google Sheets? Would be easier to use and also provides some powerful features that may be useful.

**Comment by Zmwang622** [comment]
yeah agreed airtable would be way better. Pretty swamped w other stuff rn but if you want to make a PR id be happy to merge

**Comment by aakash1104** [comment]
@Zmwang622 I can try and work on this when I have some time a little. Perhaps this issue can be kept open till then?

**Comment by Zmwang622** [comment]
Great, sounds good to me!

**Comment by KamalSinghKhanna** [comment]
hey!  is this issue still open ?

**Comment by Zmwang622** [comment]
I don't think there's been progress? If you wanna try and take it go ahead!

**Comment by aakash1104** [comment]
I wanted to take this but I have very little time so you can go ahead and take it @KamalSinghKhanna :)

**Comment by srirag-vuppala** [comment]
,

**Comment by KamalSinghKhanna** [comment]
Sorry for the late reply @aakash1104, can you explain that how to solve this issue. Do I have to replace google forms with Airtable.

**Comment by aakash1104** [comment]
The idea would be to replace the Google sheets with Airtable. Check out [this repo](https://github.com/poteto/hiring-without-whiteboards) and how Airtable is used here as a starter.

**Comment by qiaochenskr** [comment]
haha

**Comment by Aniumbott** [comment]
what is goin on here ? :)

**Comment by Zmwang622** [comment]
Not much

**Comment by Adyyousf** [comment]
hey I'm looking for my first issue to solve. can you help me in solving this one. I just want a PR for my GitHub profile.
