### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by lucas-amberg** [pittcsc/Summer2023-Internships#3101]
### Link to Internship Posting

https://www.coinbase.com/careers/positions/5455689?gh_jid=5455689&gh_src=20687b321us

### Company Name

Coinbase

### Internship Title

Software Engineer Intern, Frontend

### Location

Los Angeles, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

102396588+lucas-amberg@users.noreply.github.com

**Comment by PresidentSam100** [comment]
Already added. Also, Coinbase internships are all remote according to the job postings site (https://www.coinbase.com/careers/positions). For future remote internships, specify the location in the "Remote, [Country]" format rather than the "City, State" format.
