### ISSUE TITLE
SiriusXM Software Engineer Intern

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3102]
### Link to Internship Posting

https://careers.siriusxm.com/careers/jobs/15048?lang=en-us

### Company Name

SiriusXM

### Internship Title

Software Engineer Intern

### Location

New York City, New York

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by PresidentSam100** [comment]
The link you provided doesn't work, the job posting might have been removed or doesn't exist.

**Comment by PresidentSam100** [comment]
Just got back to this issue. The link seems to now be working as of writing this (despite it not working before). I will approve it!
