### ISSUE TITLE
Potential Maintainer for this Repo? 

### ISSUE THREAD

**Issue by PresidentSam100** [pittcsc/Summer2023-Internships#3111]
### Issue/Question

I'm considering becoming a community maintainer for this GitHub Internship repo. I've made several contributions to this repo already and it's been great getting my hands dirty with open source work. Taking it a step further by becoming a maintainer would be greatly rewarding. I'm not sure if you are still accepting any maintainers at the moment, but just throwing my interest out there hoping someone sees it :)

**Comment by yan-michael** [comment]
We are always accepting maintainers! Just shot you an email :)
