### ISSUE TITLE
[New Internship] Procter & Gamble Site Digital Technology Internship

### ISSUE THREAD

**Issue by PresidentSam100** [pittcsc/Summer2023-Internships#3139]
### Link to Internship Posting

https://www.pgcareers.com/global/en/job/R000086657/Site-Digital-Technology-Internship

### Company Name

Procter & Gamble

### Internship Title

Site Digital Technology Internship

### Location

Cincinnati, OH

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

samlu@utexas.edu

**Comment by brandon-nguyen-lam** [comment]
not relevant
