### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by ashaikh23** [pittcsc/Summer2023-Internships#3141]
### Link to Internship Posting

https://www.coinbase.com/careers/positions/5455689

### Company Name

Coinbase

### Internship Title

Summer 2024 - Software Engineer Intern, Frontend

### Location

Remote USA | Remote Canada

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

shaikh.aymaan@yahoo.com

**Comment by PresidentSam100** [comment]
Looks good! Thanks @ashaikh23
