### ISSUE TITLE
[CLOSED] Smasung Data Science Researcher Intern 

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3143]
### Link to Internship Posting

https://boards.greenhouse.io/samsungresearchamericainternship/jobs/6804869002?gh_src=13c38d562us&source=LinkedIn&utm_source=Simplify&ref=Simplify

### Company Name

Samsung

### Internship Title

Data Science Researcher Intern

### Location

Mountain View, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by PresidentSam100** [comment]
@rygeorge This is just a link to the Samsung Research America Internship postings site. Could you replace it with the original application link from the GitHub README? Thanks!

**Comment by rygeorge** [comment]
Done! Sorry about that, let me know if anything else needs to be changed :)

**Comment by PresidentSam100** [comment]
Looks good! Thank you @rygeorge :)
