### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by joseph-w0ng** [pittcsc/Summer2023-Internships#3147]
### Link to Internship Posting

https://careers.paramount.com/Paramount/job/Burbank-Software-Engineering-Intern-%28Summer-2024-NYC%2C-LA-or-Remote%29-CA-91505/1082274800/

### Company Name

Paramount

### Internship Title

Software Engineering Intern

### Location

Los Angeles, CA | New York, NY | Remote

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

**Comment by PresidentSam100** [comment]
looks good! thanks @JosephWong123
