### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by spaceybread** [pittcsc/Summer2023-Internships#3156]
### Link to Internship Posting

https://jobs.lumen.com/global/en/job/331302/Intern-Cybersecurity-Analyst?utm_source=Simplify&ref=Simplify

### Company Name

Lumen

### Internship Title

Cybersecurity Analyst

### Location

Remote

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

This internship is no longer accepting applications

**Comment by PresidentSam100** [comment]
@spaceybread All done! Thanks!
