### ISSUE TITLE
Product Designer Intern @ Duolingo

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3158]
### Link to Internship Posting

https://boards.greenhouse.io/duolingouniversityrecruitment/jobs/6982219002?gh_src=5288c6c62us

### Company Name

Duolingo

### Internship Title

Product Designer Intern

### Location

Pittsburgh, PA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by PresidentSam100** [comment]
@rygeorge looks pretty good! I haven't really seen many Product Designer Positions before, but I do see a few other Product Design positions in this repo, so I'll add it. (provided that CS majors are eligible to apply)

**Comment by rygeorge** [comment]
Yeah the job description didn't mention any specific degree but in general the wording seemed pretty similar to product design and UI/UX jobs which is why I added it. Hopefully someone using the repo gets some benefit out of it :)
