### ISSUE TITLE
Product Design Intern @ Coinbase

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3159]
### Link to Internship Posting

https://www.coinbase.com/careers/positions/5458493?gh_jid=5458493&gh_src=20687b321us

### Company Name

Coinbase

### Internship Title

Product Design Intern

### Location

Remote USA | Remote Canada

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

### Extra Notes (Optional)

Pretty sure the job location requirement is like other Coinbase positions but this req says Montreal on LinkedIn so not entirely sure. If someone wants to change it to Remote Canada/Remote U.S. feel free to do so :)

**Comment by PresidentSam100** [comment]
@rygeorge Whenever in doubt, refer to the location that's on the actual job posting page rather than LinkedIn. Could you change it to Remote as such? Thanks!

**Comment by rygeorge** [comment]
Updated! Sorry for any inconvenience I may have caused

**Comment by PresidentSam100** [comment]
@rygeorge Thank you for your contributions! Approved!
