### ISSUE TITLE
Software Developer Intern @ Konrad Summer 2024

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3162]
### Link to Internship Posting

https://www.konrad.com/careers/job/software-developer-intern-may-2024-4-months_5730015003

### Company Name

Konrad

### Internship Title

Software Developer Intern

### Location

Toronto, ON

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by PresidentSam100** [comment]
Looks good. Thanks @rygeorge
