### ISSUE TITLE
Data Analyst Intern @ RBC 

### ISSUE THREAD

**Issue by rygeorge** [pittcsc/Summer2023-Internships#3184]
### Link to Internship Posting

https://jobs.rbc.com/ca/en/job/RBCAA0088R0000067159EXTERNALENCA/2024-Winter-Student-Data-Analyst-4-months?utm_source=LinkedIn&utm_medium=phenom-feeds&utm_campaign=rbc_linkedin

### Company Name

Royal Bank of Canada

### Internship Title

Data Analyst Intern

### Location

Toronto, ON

### What term(s) is this internship offered for?

Winter 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ryan.george2@mail.mcgill.ca

**Comment by hemanthy1** [comment]
Job has expired
