### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by Frostfire25** [pittcsc/Summer2023-Internships#3204]
### Link to Internship Posting

https://www.cockroachlabs.com/careers/jobs/?gh_jid=5366373

### Company Name

Cockroach Labs

### Internship Title

Software Engineer Summer Intern (Backend)

### Location

NYC

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

Yes

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

luis1944alex@gmail.com

### Reason for edit

Appending internship

**Comment by Asevenn** [comment]
o_0

**Comment by Frostfire25** [comment]
I did not mean to open, apologies
