### ISSUE TITLE
New Feature Request: To avoid removing or omitting names of the companies.

### ISSUE THREAD

**Issue by bhooshanaj** [pittcsc/Summer2023-Internships#3212]
### Improvement

I can see a lot of internship position (expired and still open) that have no company name but instead only the link and other details. Like position and location.

I am not sure if this is an editing error or deliberate but could I request the posters/editors to not remove/omit the name of the company while posting or even after the internship is no longer available.

This would allows us to know that such and such company perhaps hires such roles every 6 months or HAVE such roles in the first place. And we can prep for an internship in the next semester or the next time we expect it to comes around.

I am not talking about the ones that are removed entirely. But about the ones that still show the other columns ( role, location, lock or Apply button and date) but the name of the company only shows a "Return" (Enter key) sign in it.

Is this deliberate? Are these internships posted by company representatives and they remove the name to prevent over-use? or perhaps to encourage people to go to Simplify (or the link provided) to check the internship instead of just looking up the company?

![Screenshot_20231109_131206](https://github.com/SimplifyJobs/Summer2024-Internships/assets/19308414/121a4977-ac8f-4d00-9c2b-fcfaa7463b01)

Thanks!

**Comment by prasad-aditya** [comment]
These all refer to the same company, which is at the top.
