### ISSUE TITLE
New Feature Request: Term (Summer or Spring or Fall)

### ISSUE THREAD

**Issue by evan-is-working** [pittcsc/Summer2023-Internships#3214]
### Improvement

Hi there!

Since the company is opening Spring, Summer, and Fall of 2024, could the developers kindly add the terms' info on this web page since some students like me are also looking for Fall or Spring CO-OP! Thanks in advance!

Best

**Comment by brandon-nguyen-lam** [comment]
There is an off-season list you can visit by going to

https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/README-Off-Season.md
