### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3220]
### Link to Internship Posting

https://careers.viasat.com/jobs/2588

### Company Name

Viasat

### Internship Title

Software Engineer Intern - Secure Network Systems

### Location

Carlsbad, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
@vanshb03 Looks good. Thank you!
