### ISSUE TITLE
Alstom - Engineering

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3229]
### Link to Internship Posting

https://jobsearch.alstom.com/job/Melbourne-%28US%29-V&V-Engineering-Intern-%28Summer-2024%29-FL-32901/997287001/

### Company Name

Alstom

### Internship Title

V&V Engineering Intern

### Location

Melbourne, FL

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by brandon-nguyen-lam** [comment]
closed
