### ISSUE TITLE
Thermo Fisher Scientific - SWE

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3238]
### Link to Internship Posting

https://jobs.thermofisher.com/global/en/job/R-01207385/Software-Engineering-Intern-Co-op-2024

### Company Name

Thermo Fisher Scientific

### Internship Title

Software Engineering Intern/Co-op 2024

### Location

Hillsboro, OR

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by kay-io** [comment]
It doesn't offer sponsorship. You might wanna update that.

**Comment by vanshb03** [comment]
Updated
