### ISSUE TITLE
added listing: Ford SWE internship

### ISSUE THREAD

**Issue by harshaldulera** [pittcsc/Summer2023-Internships#3244]
### Link to Internship Posting

https://efds.fa.em5.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/requisitions/preview/17171/apply/email?keyword=software+intern&mode=location

### Company Name

Ford

### Internship Title

2024 Software Engineering Internship

### Location

Dearborn, MI

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

harshaldulera82@gmail.com

**Comment by vanshb03** [comment]
This is for Summer 2024, as mentioned on the job page.

**Comment by harshaldulera** [comment]
fixed
