### ISSUE TITLE
added listing: Amazon SDE Intern 2024

### ISSUE THREAD

**Issue by harshaldulera** [pittcsc/Summer2023-Internships#3245]
### Link to Internship Posting

https://www.amazon.jobs/en/jobs/2408098/software-development-engineer-internship-2024-us

### Company Name

Amazon

### Internship Title

Software Development Engineer Internship - 2024 (US)

### Location

WA, Seattle

### What term(s) is this internship offered for?

Winter 2024, Summer 2024, Fall 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

harshaldulera82@gmail.com

**Comment by vanshb03** [comment]
This is a duplicate. Already on the list for Summer 2024:
Line 1297: | Amazon | Software Development Engineer Internship | Seattle, WA | <a href="https://www.amazon.jobs/en/jobs/2408098/software-development-engineer-internship-2024-us?utm_source=Simplify&ref=Simplify"><img src="https://i.imgur.com/u1KNU8z.png" width="118" alt="Apply"></a> | Aug 04 |
