### ISSUE TITLE
Wikimedia Corp. - SWE 

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3250]
### Link to Internship Posting

https://boards.greenhouse.io/wikimedia/jobs/5511020?gh_src=0e7d3b611us

### Company Name

Wikimedia Foundation

### Internship Title

Software Engineering - Intern

### Location

Remote

### What term(s) is this internship offered for?

Spring 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by Iris-Song** [comment]
Only 24 summer internship is accepted in this repo

**Comment by vanshb03** [comment]
There is a off-season section on the repo @Iris-Song
