### ISSUE TITLE
Boston Consulting Group - SRE

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3267]
### Link to Internship Posting

https://careers.bcg.com/job/BCG1US21566BREXTERNALENUS/

### Company Name

Boston Consulting Group

### Internship Title

Site Reliability Engineer - Intern

### Location

Atlanta, GA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by nb303** [comment]
Thanks for sourcing all of these 🙏 however would love to see more
internships in Toronto/Canada!

**Comment by vanshb03** [comment]
Will do :)
