### ISSUE TITLE
Neuralink - RobOpti

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3274]
### Link to Internship Posting

https://boards.greenhouse.io/neuralink/jobs/5795906003

### Company Name

Neuralink

### Internship Title

Robot Optics - Intern

### Location

Fremont, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by Iris-Song** [comment]
only SDE, Data roles are accepted

**Comment by vanshb03** [comment]
The description of the Repo said software, tech, CS, PM, quant internships @Iris-Song

**Comment by Iris-Song** [comment]
yes. But this job more like Mechanical engineering, which is not accepted
