### ISSUE TITLE
Squarespace - New Internship

### ISSUE THREAD

**Issue by ajain02** [pittcsc/Summer2023-Internships#3316]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/3771321789

### Company Name

Squarespace

### Internship Title

Software Engineer Intern - Backend (Java) or Frontend (Javascript)

### Location

New York

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
@ajain02 Change link: https://www.squarespace.com/careers/jobs/5369485
