### ISSUE TITLE
CLOSED - AlphaGrep Securities - Quant

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3354]
### Link to Internship Posting

https://boards.greenhouse.io/alphagrepsecurities/jobs/6340385002?utm_source=Simplify&ref=Simplify

### Company Name

AlphaGrep Securities

### Internship Title

Quantitative Trading Intern

### Location

Chicago, IL

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
Thanks for the contribution! @vanshb03
