### ISSUE TITLE
CLOSED - DRW - SWE

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3355]
### Link to Internship Posting

https://boards.greenhouse.io/drweng/jobs/5114577?utm_source=Simplify&ref=Simplify

### Company Name

DRW

### Internship Title

Software Developer Intern

### Location

Austin, TX | Chicago, IL

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
Looks good! Thanks @vanshb03
