### ISSUE TITLE
CLOSED - Fetch - iOS

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3356]
### Link to Internship Posting

https://boards.greenhouse.io/fetchrewards/jobs/5210272003?utm_source=Simplify&ref=Simplify

### Company Name

Fetch 

### Internship Title

iOS Apprenticeship - Mobile Engineer

### Location

Birmingham, AL

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
Looks good @vanshb03
