### ISSUE TITLE
CLOSED - Infoverity - SIP

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3358]
### Link to Internship Posting

https://infoverity.zohorecruit.com/jobs/Infoverity-USA-Careers/530797000006827069/Summer-Internship-summer-2024-?utm_source=Simplify&ref=Simplify

### Company Name

Infoverity

### Internship Title

Summer Internship Program

### Location

Dublin, OH

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
Thanks @vanshb03
