### ISSUE TITLE
CLOSED - Jane Street - SWE

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3359]
### Link to Internship Posting

https://www.janestreet.com/join-jane-street/position/6834728002/?utm_source=Simplify&ref=Simplify

### Company Name

Jane Street

### Internship Title

Software Engineer Internship

### Location

NYC

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
Sad to see that this company is closed. Maybe one of us can get this sometime later :)

**Comment by vanshb03** [comment]
Fingers crossed 🤞🏽
