### ISSUE TITLE
CLOSED - Wells Fargo - DA

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3360]
### Link to Internship Posting

https://www.wellsfargojobs.com/en/jobs/r-295402/2024-summer-internship-early-careers-analytics-data?jClickId=0f76a32d-92ba-4e35-8e19-d7a3a2b682ce&publisher=Linkedin%2520Flat%2520bid&utm_source=joveo&utm_source=Simplify&ref=Simplify

### Company Name

Wells Fargo

### Internship Title

Data Analytics - Summer 2024

### Location

Multiple

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
fun fact: my friend got this company but for SWE

**Comment by PresidentSam100** [comment]
Not sure why it's not approved. The links seem to match. Will prolly fix this sometime later.
