### ISSUE TITLE
New Feature Request: Additional Table Organization

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3361]
### Improvement

Feature Idea: internships are sorted as they are(by date added), and if they have 🔒, it moves to the bottom of the table, leaving only the currently open internships at the top.

**Comment by arnitsinha** [comment]
An amazing addition, makes it a whole lot easier to sort through internships.

**Comment by rushilsrivastava** [comment]
Closed with [e1f1062](https://github.com/SimplifyJobs/Summer2024-Internships/commit/e1f1062d4fb8b3364329d8c01fa968168c5617df)
