### ISSUE TITLE
ICE/Black Knight SWE intern- New Internship

### ISSUE THREAD

**Issue by ajain02** [pittcsc/Summer2023-Internships#3363]
### Link to Internship Posting

https://blackknight.wd1.myworkdayjobs.com/en-US/ics/details/Intern---Software-Engineer_23-840

### Company Name

ICE (Black Knight)

### Internship Title

SWE Intern

### Location

Jacksonville

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

ICE owns NYSE and Black Knight, but I think the internship is under the Black Knight workday

**Comment by vanshb03** [comment]
### Location
Jacksonville, FL
