### ISSUE TITLE
CLOSED - Infinite Campus - SWE

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3368]
### Link to Internship Posting

https://phf.tbe.taleo.net/phf03/ats/careers/requisition.jsp?org=INFINITECAMPUS&cws=1&rid=1521&utm_source=Simplify&ref=Simplify

### Company Name

Infinite Campus

### Internship Title

Software Engineer - Intern

### Location

Blaine, MN

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by PresidentSam100** [comment]
@vanshb03  Last issue I will approve for today. Will get to approving others later. Thanks for all your contributions!

**Comment by vanshb03** [comment]
> @vanshb03 Last issue I will approve for today. Will get to approving others later. Thanks for all your contributions!

Thank you for approving all from today.
