### ISSUE TITLE
Bloomber Industry Group Software Engineer Intern

### ISSUE THREAD

**Issue by justinespinal** [pittcsc/Summer2023-Internships#3375]
### Link to Internship Posting

https://bloomberg.wd1.myworkdayjobs.com/en-US/Bloombergindustrygroup_External_Career_Site/job/Arlington---1801-S-Bell-INDG/Intern--Software-Engineering_120909

### Company Name

Bloomberg Industry Group

### Internship Title

Software Engineer

### Location

Arlington, TX

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

espinaljustin03@gmail.com

**Comment by vanshb03** [comment]
### Internship Title
Software Engineer - Intern
