### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by gitvivek14** [pittcsc/Summer2023-Internships#3376]
### Link to Internship Posting

https://boards.greenhouse.io/latitude/jobs/5483263?utm_source=Simplify&ref=Simplify

### Internship Title

2024 Summer Internship: Software Engineer - Backend

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

varora2004@gmail.com

### Reason for edit

This Internship is no Longer Available.
Please Remove this Internship from the List.
This is posted on  Nov6

**Comment by gitvivek14** [comment]
Internship no longer Available..

**Comment by vanshb03** [comment]
Duplicate thread, made it already: https://github.com/SimplifyJobs/Summer2024-Internships/issues/3373
