### ISSUE TITLE
Penn State University - R&D

### ISSUE THREAD

**Issue by vanshb03** [pittcsc/Summer2023-Internships#3381]
### Link to Internship Posting

https://psu.wd1.myworkdayjobs.com/en-US/PSU_Staff/job/Penn-State-University-Park/Guidance-and-Control-Research---Development-Internship_REQ_0000050698-1

### Company Name

Penn State University

### Internship Title

Guidance and Control Research & Development - Intern

### Location

State College, PA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

bataviyavansh@gmail.com

**Comment by brandon-nguyen-lam** [comment]
not a standard application process for non penn-state students so i'm not adding it
