### ISSUE TITLE
Cap1 TIP - New Internship

### ISSUE THREAD

**Issue by ajain02** [pittcsc/Summer2023-Internships#3399]
### Link to Internship Posting

https://www.capitalonecareers.com/job/-/-/234/57932226048?p_sid=MD4n9qb&p_uid=s5vgKrve8t&source=rd_linkedin_job_posting_tm&ss=paid&utm_campaign=capone_all_jobs_23&utm_content=pj_board&utm_medium=jobad&utm_source=linkedin+slotted&dclid=CKTslp2j6oIDFecRigMdUk4IMg

### Company Name

Capital One

### Internship Title

TIP

### Location

Richmond, Virginia | Philadelphia, Pennsylvania | Roswell, Georgia | Plano, Texas

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
The link you provided is not valid – can you please double check?
