### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by mwam-hackathon** [pittcsc/Summer2023-Internships#3430]
### Link to Internship Posting

https://www.mwam.com/news/internships/new-york-technology-internship/

### Company Name

Marshall Wace

### Internship Title

Technology Internship (Summer 2024)

### Location

New York, NY

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by athul-22** [comment]
Hai
