### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by Slijeff** [pittcsc/Summer2023-Internships#3465]
### Link to Internship Posting

https://boards.greenhouse.io/andurilindustries/jobs/4159665007?utm_source=Simplify&ref=Simplify

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

I think this position requires U.S. citizenship since the required qualification says "U.S. Person status is required as this position needs to access export controlled data."

**Comment by PresidentSam100** [comment]
@Slijeff Thanks for bringing this up.
