### ISSUE TITLE
New Internship - Institute for Computing in Research

### ISSUE THREAD

**Issue by markgalassi** [pittcsc/Summer2023-Internships#3532]
### Link to Internship Posting

https://computinginresearch.org/summer-research-internship-program-2024/

### Company Name

Institute for Computing in Research

### Internship Title

Research Intern

### Location

Santa Fe NM | Portland OR | Austin TX

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

mark@galassi.org

### Extra Notes (Optional)

High School internship for students finishing 10th, 11th, and 12th grade.  Research in all areas.  Modeled after the Los Alamos National Laboratory student programs.

**Comment by yan-michael** [comment]
Sorry this list is for college students only!
