### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by Shalaby1022** [pittcsc/Summer2023-Internships#3562]
### Link to Internship Posting

https://teamremotely.zohorecruit.eu/jobs/Careers/64526000011293214/Junior-Software-Developer-Trainee?source=LinkedIn&embedsource=LinkedIn%2BLimited%2BListings

### Company Name

Team Remotely Inc.

### Internship Title

Junior Software Developer Trainee

### Location

Las Vegas, NV | Remote

### What term(s) is this internship offered for?

Winter 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ahmed.ibrahiem160016@ci.menofia.edu.eg

**Comment by yan-michael** [comment]
Posting closed
