### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by andrewhong04** [pittcsc/Summer2023-Internships#3570]
### Link to Internship Posting

https://app.ripplematch.com/v2/public/job/f1076b21/details?utm_source=Simplify&ref=Simplify

### Company Name

Figma

### Internship Title

Data Science Intern (2024)

### Location

San Francisco, CA New York, NY

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [X] Yes, remove this internship

### Email associated with your GitHub account (Optional)

andrew.jwn.hong@gmail.com

### Reason for edit

No longer accepting applications.

**Comment by yan-michael** [comment]
We shouldnt remove the internshiip but instead mark it as not accepting apps

**Comment by rheayohn8** [comment]
I would love to have a remote inernship opportunity! 

connection ~~~~https://profile.indeed.com/p/rheay-10z443f 

```
# 3481
```
-_

**Comment by poornimajd** [comment]
From the last 5 days there have been no new internships posted, when can we expect the new ones to be posted?
