### ISSUE TITLE
Global-Network-And-Technology-Summer-2024

### ISSUE THREAD

**Issue by Umangjain16** [pittcsc/Summer2023-Internships#3580]
### Link to Internship Posting

https://mycareer.verizon.com/jobs/r-1026139/global-network-and-technology-summer-2024-internship-opportunity/

### Company Name

Verizon

### Internship Title

ML or Software Engineer Internship

### Location

Hybrid

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

umang.jain.16july@gmail.com

**Comment by AymanTheTinkerer** [comment]
link is dead
