### ISSUE TITLE
Why no new internship listings?

### ISSUE THREAD

**Issue by FreeUserIam** [pittcsc/Summer2023-Internships#3589]
### Issue/Question

Why has there been a stop in new internship listings?

**Comment by rushilsrivastava** [comment]
@AlanChen4 is looking into this!

**Comment by anakita** [comment]
By any chance is there any expected timeline as to when the issue will be resolved? It has been 7 days in a row now.

**Comment by hnimees** [comment]
The issue should be resolved now! Please note that the list will continually update through the day.
