### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by aegdet** [pittcsc/Summer2023-Internships#3594]
### Link to Internship Posting

https://www.thefreshdev.com/job/software-engineer-intern-summer-2024-harbinger-motors-1037

### Company Name

Harbinger Motors

### Internship Title

Software Engineer - Intern

### Location

Garden Grove, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
This is a job board, not a listing
