### ISSUE TITLE
The copilot extension is no longer on Mozilla's addon store

### ISSUE THREAD

**Issue by BossDaily** [pittcsc/Summer2023-Internships#3597]
### Issue/Question

Is there a reason why the extension is removed from Mozilla's addon store for Firefox? Its not available anymore, when I visit the [original link](https://addons.mozilla.org/en-US/firefox/addon/simplify-jobs/) it just says the item is no longer available. It is also available in the Chrome web-store, just not on the Firefox addon store.

**Comment by rushilsrivastava** [comment]
Hey, this repo isn't for Simplify support. Please visit [Simplify support](https://simplify.jobs/support) for help regarding Simplify!
