### ISSUE TITLE
COPILOT EXTENSION: No longer available on Firefox

### ISSUE THREAD

**Issue by MMachado05** [pittcsc/Summer2023-Internships#3644]
### Issue/Question

I wasn't able to find a repo for the Simplify Copilot extension itself, however I did find an [issue](https://github.com/SimplifyJobs/Summer2024-Internships/issues/2563) relating to the extension on this repo that was openly received, so I figure this would be okay to post here.

Simply, the link to the [Copilot extension for Firefox](https://addons.mozilla.org/en-US/firefox/addon/simplify-jobs/) is dead. On the official Simplify [website](https://simplify.jobs/copilot), I've also noticed that the download link for the extension only says "Add to Chrome," which suggests that the extension is simply no longer available for Firefox. Has the FF extension been sunsetted? Or is something else going on?

**Comment by yan-michael** [comment]
We're working on a fix!

**Comment by MMachado05** [comment]
Awesome to hear! Any info on when we can expect the extension page to be back up? I only recently switched to Firefox and applying to internship positions and such is such a pain without the extension... 😅 Love the work you guys do!

**Comment by assadyousuf** [comment]
@yan-michael This is still an issue as of today. Super frustrating for fire fox users

**Comment by d1amondb0t** [comment]
@yan-michael same here, the extension is no longer available on the firefox add-ons page.

**Comment by yan-michael** [comment]
Hey! Unfortunately, Firefox is being a major PITA and has been consistently removing the Simplify Add-on from the store every other week for entirely bogus reasons.

We don't have an ETA on when this will be resolved, as we are entirely dependent on the Mozilla team. If you want to use Simplify Copilot today, the best option would be a Chromium browser

**Comment by MMachado05** [comment]
@yan-michael Would it be possible to provide a standalone `xpi` file for Firefox users as a workaround? That way we could install and update the extension independent of the extension's approval on the Firefox Add-On center.
