### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by JesNi523** [pittcsc/Summer2023-Internships#3679]
### Link to Internship Posting

https://jobs.lumen.com/global/en/job/331383/Intern-Data-Science-Summer-2024?utm_source=Simplify&ref=Simplify

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

**Comment by yan-michael** [comment]
Application closed.
