### ISSUE TITLE
Amazon Robotics

### ISSUE THREAD

**Issue by divepile** [pittcsc/Summer2023-Internships#3754]
### Link to Internship Posting

https://www.amazon.jobs/en/jobs/2545578/amazon-robotics-software-development-engineer-co-op-fall-2024

### Company Name

Amazon Robotics

### Internship Title

Software Development Engineer Co-Op (July to December 2024)

### Location

Westborough, MA

### What term(s) is this internship offered for?

Summer 2024, Fall 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by leilaxle** [comment]
Internship has been added to the list.
