### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by bhavyapandya** [pittcsc/Summer2023-Internships#3756]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/data-analytics-intern-at-lamb-weston-3851024089/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic

### Company Name

Lamb Weston

### Internship Title

Data Analytics Intern

### Location

Kennewick, WA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by leilaxle** [comment]
Internship has been added to the list.
