### ISSUE TITLE
New Internship at Black Swan (Cyber Defense Labs)

### ISSUE THREAD

**Issue by ColtenMikulastik** [pittcsc/Summer2023-Internships#3811]
### Link to Internship Posting

https://airtable.com/appxANROWCbnwcONZ/shrel6YB8b26YsOgE

### Company Name

Blackswan Cybersecurity

### Internship Title

Intern

### Location

Dallas TX | Remote

### What term(s) is this internship offered for?

Spring 2024, Summer 2024, Fall 2024

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

mikulastikc@gmail.com

### Extra Notes (Optional)

Black Swan is a Managed Security Service Provider, that employs Security Analysts in a 24/7 Security Operations Center setting.

**Comment by rushilsrivastava** [comment]
Hey! Unfortunately, this doesn't meet our quality standards of approved listings
