### ISSUE TITLE
New Feature Request: Will you have a new github repo for 2025 summer internship!

### ISSUE THREAD

**Issue by evan-dayy** [pittcsc/Summer2023-Internships#3958]
### Improvement

Hi there!!

Thanks for you guys' hard work for carrying out 2024 summer internships!!! As the season is approaching to the end,  is there a seperated 2025 swe internships repo be published in the near future?

Thanks again!
Best,

**Comment by rushilsrivastava** [comment]
Hey! We will transition this repo to a 2025 repo in the coming weeks!
