### ISSUE TITLE
2025 New-grad/2025-internship Update!

### ISSUE THREAD

**Issue by zionsc** [pittcsc/Summer2023-Internships#3970]
### Issue/Question

Hey all! I was just wondering about the timeline of when the 2025 new grad and 2025 internship update would happen for this repo.

Thanks again!

**Comment by yan-michael** [comment]
In the next week or so!

**Comment by sir-mole** [comment]
so how do we apply ..

**Comment by yan-michael** [comment]
Internship repo is updated!
