### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by rutvikrau21** [pittcsc/Summer2023-Internships#3977]
### Link to Internship Posting

https://tally.so/r/woAg6X

### Company Name

VecFlow AI

### Internship Title

Full-Stack, Backend, ML Engineering Intern

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

No

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

This internship is no longer accepting applications

**Comment by Nishchaypat** [comment]
Hello Rutvik, 

Can I work on this? If so could you assign it to me please?

**Comment by leilaxle** [comment]
Internship is still active
