### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by tjohnson012** [pittcsc/Summer2023-Internships#4011]
### Link to Internship Posting

https://jobs.boeing.com/job/seattle/virginia-tech-2025-engineering-summer-internship-program/185/66513981104

### Company Name

Virginia Tech

### Internship Title

Summer Internship Program

### Location

Sure, here are the locations separated by pipes:  Seattle, Washington | Hill Air Force Base, Utah | Huntsville, Alabama | Portland, Oregon | Richmond, Virginia | Washington D.C., District of Columbia | Tinker Air Force Base, Oklahoma | Oklahoma City, Oklahoma | Madison, Alabama | Leesburg, Virginia | Arlington, Virginia | Helena, Montana | North Charleston, South Carolina | Heath, Ohio | Englewood, Colorado | Fairfax, Virginia | Colorado Springs, Colorado | Seal Beach, California | Maryland Heights, Missouri | Chantilly, Virginia | Dallas, Texas | Virginia Beach, Virginia | Springfield, Virginia | Pleasanton, California | San Antonio, Texas | San Luis Obispo, California | Saint Charles, Missouri | Salt Lake City, Utah | Charleston, South Carolina | Smithfield, Pennsylvania | Orlando, Florida | Berkeley, Missouri | Miami, Florida | Huntington Beach, California | Hazelwood, Missouri | Germantown, Maryland | El Segundo, California | Albuquerque, New Mexico | Fort Walton Beach, Florida | Titusville, Florida | China Lake Acres, California | Herndon, Virginia | Swansea, Illinois | O'Fallon, Illinois | Ridley Park, Pennsylvania | Tukwila, Washington | John F Kennedy Space Center, Florida | Jacksonville, Florida | Edwards Air Force Base, California | Scott Air Force Base, Illinois | Mountain View, California | Houston, Texas | California, Maryland | Belleville, Illinois | Mukilteo, Washington | Long Beach, California | Puyallup, Washington | Renton, Washington | Mascoutah, Illinois | Layton, Utah | Los Angeles, California | Auburn, Washington | Philadelphia, Pennsylvania | Everett, Washington | Kent, Washington | Mesa, Arizona | New Orleans, Louisiana

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

johns7to@mail.uc.edu

### Extra Notes (Optional)

Full time undergraduate December 2025 - June 2026

**Comment by yan-michael** [comment]
This is specific to a school

**Comment by tjohnson012** [comment]
it says at the bottom enrolled in undergraduate institution or virginia tech

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
