### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by harshit240205** [pittcsc/Summer2023-Internships#4017]
### Link to Internship Posting

https://wellfound.com/jobs/3040541-front-end-engineer-intern

### Company Name

Socialsence

### Internship Title

Front end Intern

### Location

Remote

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

parmarharshit2402@gmail.com

### Extra Notes (Optional)

I am adding an internship related to Front end.

**Comment by hemanthy1** [comment]
Seems like the internship is for remote in India
