### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by lcasasp** [pittcsc/Summer2023-Internships#4024]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/86639017272976070-software-engineering-intern-bs-summer-2025?utm_source=Simplify&ref=Simplify

### Company Name

Google

### Internship Title

Software Engineering Internship

### Location

All US Locations

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship still accepting applications?

No

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

lucascasasp@icloud.com

### Reason for edit

Google has closed their application.

**Comment by hemanthy1** [comment]
Already updated
