### ISSUE TITLE
Editing Internship - Google SWE BS Intern 2025

### ISSUE THREAD

**Issue by Logan-Roche** [pittcsc/Summer2023-Internships#4025]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/86639017272976070-software-engineering-intern-bs-summer-2025?utm_source=Simplify&ref=Simplify

### Company Name

Google

### Internship Title

Google SWE BS Intern 2025

### Location

United States

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

No

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

ljroche04@gmail.com

### Reason for edit

This internship post is no longer available.

**Comment by hemanthy1** [comment]
Already removed
