### ISSUE TITLE
Editing Internship - Cranium AI/ML Engineer Internship Summer 2025

### ISSUE THREAD

**Issue by arunike** [pittcsc/Summer2023-Internships#4027]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/3925803158/?alternateChannel=search&refId=CUPJ7%2FmdAYQXkO%2FkeNhM1A%3D%3D&trackingId=S3o5%2F80RMhaLqIA%2BqE%2FsEg%3D%3D&trk=d_flagship3_search_srp_jobs

### Company Name

Cranium

### Internship Title

AI/ML Engineer Intern

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

Yes

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

r631137986@gmail.com

### Reason for edit

This link to the internship is invalid

**Comment by hemanthy1** [comment]
Hello, I just checked the link to the Cranium internship currently on the repo and it directs you to the Easy Apply page on LinkedIn for the company properly.
