### ISSUE TITLE
Software Engineer I Internship | Cisco

### ISSUE THREAD

**Issue by hashlol** [pittcsc/Summer2023-Internships#4028]
### Link to Internship Posting

https://github.com/SimplifyJobs/Summer2025-Internships

### Company Name

Cisco

### Internship Title

Software Engineer I 

### Location

San Jose, California, US | Atlanta, GA | Ann Arbor, MI | Austin, TX | Seattle, WA | RTP, NC |  San Francisco, CA | Richardson, TX | Maynard, MA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

muhshim683@gmail.com

**Comment by hemanthy1** [comment]
Hi, can you please update this with the link to the posting itself (instead of a link to our repository). Also, just a reminder, this repository is for internships only, new grad roles should go in the new grad repository
