### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by VanshGehlot** [pittcsc/Summer2023-Internships#4037]
### Link to Internship Posting

https://jobs.dolby.com/careers/job/23456914-research-intern-san-francisco-california-united-states?pid=23456914&recommended=1

### Company Name

Dolby

### Internship Title

Research Intern

### Location

San Francisco, California, United States

### What term(s) is this internship offered for?

Fall 2025, Winter 2025, Spring 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

gehlotvansh111@gmail.com

**Comment by yan-michael** [comment]
this is PHD only
