### ISSUE TITLE
<issue>

### ISSUE THREAD

**Issue by pmfeen** [pittcsc/Summer2023-Internships#4039]
### Issue/Question

How do you get these postings? Many are private and not able to be seen on public boards. Also, some of the postings seem as if they aren't updated? For example, the Optiver SWE roles ask for a graduation date of June 2025 for a summer 2025 internship, and none of them can be seen on public boards. Is this really the official application?

**Comment by yan-michael** [comment]
We encourage community contributions from native company career pages – our team cross checks them to ensure accuracy before adding them to our board.

This particular instance seems like a hiccup on Optiver's side – looks like they've since taken down the positions.
