### ISSUE TITLE
Apple's Software Engineering Internships

### ISSUE THREAD

**Issue by mabdullahsaqib** [pittcsc/Summer2023-Internships#4040]
### Link to Internship Posting

https://jobs.apple.com/en-us/details/200554359/software-engineering-internships?team=STDNT

### Company Name

Apple

### Internship Title

Software Engineering Internships

### Location

United States

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by hemanthy1** [comment]
This is already present in the repo
