### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by JihuiTanUchicago** [pittcsc/Summer2023-Internships#4056]
### Link to Internship Posting

https://apply.workable.com/capula-investment-management-ltd/j/CADD57CDA5/

### Company Name

Capula

### Internship Title

Trading and Research Summer Internship

### Location

New York, New York, United States

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

tanjihui@uchicago.edu

**Comment by Maestro-Emi** [comment]
https://www.notion.so/MSP-f4bf39d08a954c1e9300e340854e6594
