### ISSUE TITLE
New Feature Request: Specify Level of Education Required

### ISSUE THREAD

**Issue by notsaad** [pittcsc/Summer2023-Internships#4079]
### Improvement

Would be nice to be able to see required level of schooling for a posted internship. For example the recently posted [Snowflake Data Science Intern](https://boards.greenhouse.io/embed/job_app?token=7559273002&utm_source=Simplify&ref=Simplify) position requires being enrolled in a masters or PhD program. Perhaps specify if being enrolled in a graduate program is required in the readme.

**Comment by yan-michael** [comment]
Noted. All roles are intended to be for undergraduates only
