### ISSUE TITLE
Business Analyst Intern @ Capital One - Summer 2025

### ISSUE THREAD

**Issue by Tar-ive** [pittcsc/Summer2023-Internships#4080]
### Link to Internship Posting

https://www.capitalonecareers.com/job/mclean/business-analyst-intern-summer-2025/31238/67304841712

### Company Name

Capital One 

### Internship Title

Business Analyst Intern

### Location

McLean, Virginia | Richmond, Virginia | Plano, Texas | New York, New York | Chicago, Illinois

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

tarive22@gmail.com

**Comment by brandon-nguyen-lam** [comment]
not related enough to the jobs we want on this repo
