### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by Noir01** [pittcsc/Summer2023-Internships#4095]
### Link to Internship Posting

https://www.amazon.jobs/en/jobs/2705684/software-development-engineer-intern

### Company Name

Amazon

### Internship Title

Software Development Engineer Intern

### Location

Boston, MA

### What term(s) is this internship offered for?

Fall 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

63553175+Noir01@users.noreply.github.com

**Comment by reddoy** [comment]
I dont see any information on this being for the Fall 2025 term?
