### ISSUE TITLE
Notion 

### ISSUE THREAD

**Issue by AdriM650** [pittcsc/Summer2023-Internships#4101]
### Link to Internship Posting

https://app.ripplematch.com/v2/public/company/notion?tl=1edfe69a

### Company Name

Notion

### Internship Title

Software Engineer Intern

### Location

San Francisco, CA | NYC, New York

### What term(s) is this internship offered for?

Summer 2025, Winter 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by reddoy** [comment]
Added this one from another issue!
