### ISSUE TITLE
Quantiq Partners Software Developer Internship (Summer 2025)

### ISSUE THREAD

**Issue by NebulaNomad152** [pittcsc/Summer2023-Internships#4111]
### Link to Internship Posting

https://quantiqpartners.zohorecruit.com/forms/1965216ed406321a2f6e355156f0e94ea7405c37b4ef00a027ca731b06e9be8d

### Company Name

Quantiq Partners

### Internship Title

Software Developer Internship (Summer 2025)

### Location

Austin, TX

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

**Comment by reddoy** [comment]
This is just a link to the careers page. Please input the link to the posting!
