### ISSUE TITLE
Microsoft SWE

### ISSUE THREAD

**Issue by ajohnofficial001** [pittcsc/Summer2023-Internships#4157]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/share/1751922/?utm_source=Job Share&utm_campaign=Copy-job-share

### Company Name

Microsoft

### Internship Title

Software Engineer Intern

### Location

Redmond, Washington

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ajohnofficial2020@gmail.com

**Comment by dumax315** [comment]
alternative link: https://jobs.careers.microsoft.com/us/en/job/1751922/Software-Engineer-Fullstack-Intern-Opportunities-for-University-Students-Redmond
