### ISSUE TITLE
New Internship - Kosh

### ISSUE THREAD

**Issue by haoz1119** [pittcsc/Summer2023-Internships#4168]
### Link to Internship Posting

https://koch.avature.net/en_US/careers/JobDetail/160838?src=LinkedIn#

### Company Name

Kosh 

### Internship Title

Software Engineer/Developer Intern

### Location

Wichita, Kansas

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

tristanchow.1999@gmail.com

**Comment by reddoy** [comment]
The link is broken
