### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by JorgeICS** [pittcsc/Summer2023-Internships#4169]
### Link to Internship Posting

https://simplify.jobs/p/449c21e3-67b3-4ee8-91d9-ed2d33d29780/Data-Analyst--Co-Op

### Company Name

Capital One

### Internship Title

Technology Internship Program - Summer 2025

### Location

Toronto, ON, Canada

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

No

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

jorgeicsreal@gmail.com

### Reason for edit

The summer program no longer accepts requests, but there is a new program with the same requirements for winter 2025 published  august 15

**Comment by reddoy** [comment]
I just checked the job application and it seems they are still taking applications. Where did you see that they are not?

**Comment by JorgeICS** [comment]
"It would be more accurate to say that the link appearing in the list (Capital One) is for a winter program, and also the link in the 'Apply' tab says that it no longer exists."
