### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by kambhani** [pittcsc/Summer2023-Internships#4190]
### Link to Internship Posting

https://careers.freddiemac.com/us/en/job/JR13564/Technology-Intern-Summer-2025-Hybrid-3-Days-in-Office

### Company Name

Freddie Mac

### Internship Title

Technology Intern - Summer 2025

### Location

McLean, VA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

No

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kraghuranish@gmail.com

**Comment by DestroyerAlpha** [comment]
Mark does this internship offer sponsorship as No

**Comment by kambhani** [comment]
> Mark does this internship offer sponsorship as No

Done
