### ISSUE TITLE
New Internship - Robinhood

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4196]
### Link to Internship Posting

https://app.joinhandshake.com/stu/postings?page=1&per_page=25&sort_direction=desc&sort_column=default&query=robinhood

### Company Name

Robinhood

### Internship Title

Web/ Software Engineer Intern

### Location

Hybrid

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by abdullahahmed001** [comment]
When I open the link, I can’t find the internship for Robinhood.

**Comment by LuaanNguyen** [comment]
https://app.ripplematch.com/v2/public/job/f6d4d8b9?tl=58c02b67&from_page=tracking_link 

Here's the updated link!
