### ISSUE TITLE
New Internship - ServiceNow

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4226]
### Link to Internship Posting

https://www.wayup.com/i-j-ServiceNow-007300767866403/

### Company Name

ServiceNow

### Internship Title

Software Engineer Intern

### Location

Santa Clara, CA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by GaryZhous** [comment]
this listing is no longer accepting applications...
