### ISSUE TITLE
New Internship - Grainer

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4227]
### Link to Internship Posting

https://jobs.grainger.com/job/CHICAGO-GTG-Intern-Software-Engineer-IL-60661-4555/1203361600/

### Company Name

Grainger

### Internship Title

Software Engineer Intern 

### Location

Chicago, IL

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by yan-michael** [comment]
Fixed typos
