### ISSUE TITLE
New Internship - UPS 2025 summer intern

### ISSUE THREAD

**Issue by Ziqi-M** [pittcsc/Summer2023-Internships#4231]
### Link to Internship Posting

https://www.jobs-ups.com/job/-/-/1187/69216247280

### Company Name

UPS

### Internship Title

Technology Group Summer 2025 Internship

### Location

Parsippany, NJ

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

weicureco@gmail.com

**Comment by austinhuang0131** [comment]
I get immediate rejection upon applying, I think there might be hidden conditions

**Comment by Ziqi-M** [comment]
> I get immediate rejection upon applying, I think there might be hidden conditions

Same here. I chose "I need sponsor in the future", it might be the reason.
