### ISSUE TITLE
TD Opportunity is in French?

### ISSUE THREAD

**Issue by DereC4** [pittcsc/Summer2023-Internships#4240]
### Link to Internship Posting

https://td.wd3.myworkdayjobs.com/fr-CA/TD_Bank_Careers/job/Mount-Laurel-New-Jersey/XMLNAME-2025-Summer-Internship-Program----Platforms---Technology---Software-Engineer_R_1365598?utm_source=Simplify&ref=Simplify

### Company Name

TD

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

None

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Why is the opportunity for this company in french? I think the person who linked it might have accidentally used the french version, or they were applying in french. 

(or maybe it's not french and im just dumb)

**Comment by GaryZhous** [comment]
My bad, I am in Canada :/
