### ISSUE TITLE
Adobe Summer 2025 Internship

### ISSUE THREAD

**Issue by devabhixda** [pittcsc/Summer2023-Internships#4242]
### Link to Internship Posting

https://careers.adobe.com/us/en/job/ADOBUSR147746EXTERNALENUS/2025-Intern-Software-Engineer

### Company Name

Adobe

### Internship Title

Software Engineer Intern

### Location

 San Jose

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by Ziqi-M** [comment]
San Jose, CA | Austin, TX | San Francisco, CA | Lehi, UT | Seattle, WA | New York, NY
 
 Please update the locations, thanks!
