### ISSUE TITLE
New Internship - Watershed

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4260]
### Link to Internship Posting

https://job-boards.greenhouse.io/watershedclimate/jobs/4096445004

### Company Name

Watershed

### Internship Title

Software Engineer Intern

### Location

San Francisco, CA 

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

### Extra Notes (Optional)

Only accept undergraduate juniors.

**Comment by brandon-nguyen-lam** [comment]
Can you remove the Onsite & Hybrid part in the location?

**Comment by LuaanNguyen** [comment]
I've removed it.
