### ISSUE TITLE
New Internship - Ally

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4261]
### Link to Internship Posting

https://ally.avature.net/careers/JobDetail?jobId=11925&source=Handshake

### Company Name

Ally

### Internship Title

2025 Early Talent – Technology - Software Engineering / Software Development 

### Location

Charlotte, NC | Detroit, MI 

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by DereC4** [comment]
Why are they asking for the last four digits of my social security number 😭

**Comment by LuaanNguyen** [comment]
I haven't applied for it yet, I didn't know why they ask for it 😑

**Comment by brandon-nguyen-lam** [comment]
new grad role, not internship
