### ISSUE TITLE
New Internship - Qorvo 

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4262]
### Link to Internship Posting

https://careers.qorvo.com/job/Software-Engineering-Intern-CA/1207468600/

### Company Name

Qorvo

### Internship Title

Software Engineer Intern

### Location

San Jose, CA, US 

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by brandon-nguyen-lam** [comment]
Can you remove the Onsite part in the location?

**Comment by LuaanNguyen** [comment]
I've fixed it.
