### ISSUE TITLE
New Internship - Datadog

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4279]
### Link to Internship Posting

https://stryker.wd1.myworkdayjobs.com/StrykerCareers/job/Indiana-Fort-Wayne-1950-West-Cook-Road/Summer-2025-Intern---Software-Engineering---Indiana_R527310?utm_source=Simplify

### Company Name

Datadog

### Internship Title

Software Engineer Intern

### Location

Fort Wayne, Indiana

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by brandon-nguyen-lam** [comment]
this isn't datadog, it's stryker
