### ISSUE TITLE
New Internship - CNH

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4280]
### Link to Internship Posting

https://careers-cnhind.icims.com/jobs/26236/software-engineer-intern/job?mode=apply&iis=LinkedIn

### Company Name

CNH

### Internship Title

Software Engineer Intern

### Location

Sioux Falls, SD | Oak Brook, IL

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by GaryZhous** [comment]
oops, the link you provided is a bit weird and I fixed it in another issue
