### ISSUE TITLE
New Internship - Iridium 

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4282]
### Link to Internship Posting

https://careers-iridium.icims.com/jobs/4049/intern%2c-software-development/job?mode=submit_apply&ref=Simplify&src=Simplify&utm_source=Simplify

### Company Name

Iridium

### Internship Title

Software Development Intern

### Location

Chandler, AZ

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by GaryZhous** [comment]
can you fix the link? it directs me to the login page instead of the job description page
