### ISSUE TITLE
New Internship - Okta

### ISSUE THREAD

**Issue by LuaanNguyen** [pittcsc/Summer2023-Internships#4301]
### Link to Internship Posting

https://www.okta.com/company/careers/software-engineer-intern-summer-2025-6233281/?gh_src=7j0um41

### Company Name

Okta

### Internship Title

Software Engineer Intern

### Location

US | Canada

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

### Extra Notes (Optional)

Okta offers 12 week internships in the U.S. in the Summer and 16 week co-ops in Canada.

**Comment by yan-michael** [comment]
This is already in our repo!
