### ISSUE TITLE
Archiving intern position

### ISSUE THREAD

**Issue by nothans** [pittcsc/Summer2023-Internships#4315]
First, we had an overwhelming response for our intern position here. There are lots of great candidates. What is the protocol for editing/archiving/removing a job listing? What have you done before? I want to follow the pattern. Thank you!

**Comment by yan-michael** [comment]
What position is this referring to?

**Comment by nothans** [comment]
MathWorks

**Comment by yan-michael** [comment]
Please refer to our contribution guide and create an issue to close the position! :)
