### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by seanlewertow** [pittcsc/Summer2023-Internships#4346]
### Improvement

Does this repo also include computer engineering/ee/industrial & other non software roles?

I've seen a couple including embedded systems & product engineering etc, but how often? Or is it just that those roles don't come out as often or isnt as hot like swe/quant etc roles .

The reason i ask is because i am apart of a diverse engineering org at UF and i like to promote your repo.

**Comment by yan-michael** [comment]
Hey Sean! We try to include systems + product eng roles but like you mentioned there are generally fewer of those as compared to swe roles. Hope this helps! :)

**Comment by seanlewertow** [comment]
Ok, thanks! I incorportated this repo into a bot for our discord and it's been amazing so far. Yall are the best.
