### ISSUE TITLE
Uber Internship Posting Doesn't Exist

### ISSUE THREAD

**Issue by omarmneimneh** [pittcsc/Summer2023-Internships#4383]
### Link to Internship Posting

n/a

### Company Name

Uber

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

None

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

Internship posting doesn't exist

**Comment by DereC4** [comment]
can confirm, my disappointment is immeasurable and my day is ruined

**Comment by GaryZhous** [comment]
it is open now!
