### ISSUE TITLE
Web Development Internship

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4419]
### Link to Internship Posting

https://wuzzuf.net/internship/sd7A3Sg019pL-Web-Development-Internship-Osolutions-Cairo-Egypt?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic

### Company Name

Osolutions

### Internship Title

Web Development

### Location

Egypt

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
Not in target locations
