### ISSUE TITLE
Front End Developer Internship

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4420]
### Link to Internship Posting

https://wuzzuf.net/internship/88o80NUUVrwd-Front-End-Developer-KazaTech-Integrated-Solutions-Cairo-Egypt?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic

### Company Name

KazaTech Integrated Solutions

### Internship Title

Front End

### Location

Cairo, Egypt

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
Not in target locations
