### ISSUE TITLE
2025 Software Dev Engineer Intern

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4421]
### Link to Internship Posting

https://www.amazon.jobs/en/jobs/2772422/2025-software-dev-engineer-intern-germany?cmpid=DA_INAD200785B

### Company Name

Amazon Web Services Development Center Germany GmbH - R28 Logo Amazon Web Services Development

### Internship Title

Software Dev Engineer Intern

### Location

Germany Berlin

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
Not in target locations
