### ISSUE TITLE
Software Engineer Internship

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4422]
### Link to Internship Posting

https://careers.honeywell.com/us/en/job/HONEUSREQ464960EXTERNALENUS/Software-Engineer-Internship-Working-Student-or-Thesis-Opportunity?utm_source=indeed&utm_medium=phenom-feeds

### Company Name

Honeywell

### Internship Title

Software Engineer Internship

### Location

BADEN WURTTEMBERG, 68163, Germany 

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
Not in target locations
