### ISSUE TITLE
Internship / Working Student: Software engineer

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4423]
### Link to Internship Posting

https://gmv.csod.com/ux/ats/careersite/4/home/requisition/2533?c=gmv&lang=en-US

### Company Name

gmv

### Internship Title

Internship / Working Student: Software engineer

### Location

Darmstadt, Hesse, Germany

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
Not in target locations

**Comment by Mohamed-khaled0** [comment]
Ok
