### ISSUE TITLE
Software Frontend engineer (Internship)

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4427]
### Link to Internship Posting

https://www.maritimedatasystems.com/index.php/job/software-frontend-engineer-internship/

### Company Name

Maritime Data Systems GmbH

### Internship Title

Software Frontend engineer (Internship)

### Location

Hamburg, North Germay, 22301, Germany

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by brandon-nguyen-lam** [comment]
this repo is for us/canada
