### ISSUE TITLE
INTERNSHIP SOFTWARE ENGINEER (F/M/D)

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4428]
### Link to Internship Posting

https://www.handy-games.com/en/jobs/internship-software-engineer-f-m-d/

### Company Name

HandyGames 

### Internship Title

INTERNSHIP SOFTWARE ENGINEER (F/M/D)

### Location

Germany

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by brandon-nguyen-lam** [comment]
this repo is for us/canada
