### ISSUE TITLE
Internship in embedded software development 

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4429]
### Link to Internship Posting

https://recruitingapp-2845.umantis.com/Vacancies/30314/Application/New/2

### Company Name

 HILTI

### Internship Title

Internship in embedded software development 

### Location

Munich

### What term(s) is this internship offered for?

Winter 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by brandon-nguyen-lam** [comment]
this repo is for us/canada
