### ISSUE TITLE
Software  Internship

### ISSUE THREAD

**Issue by Mohamed-khaled0** [pittcsc/Summer2023-Internships#4430]
### Link to Internship Posting

https://smartapply.indeed.com/beta/indeedapply/form/contact-info

### Company Name

Software Defined Automation GmbH

### Internship Title

Software  Internship

### Location

Germany

### What term(s) is this internship offered for?

Winter 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by brandon-nguyen-lam** [comment]
this repo is for us/canada
