### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by maxgoldberg25** [pittcsc/Summer2023-Internships#4454]
### Link to Internship Posting

https://jobs.thecignagroup.com/us/en/summer-internship-program

### Company Name

Cigna

### Internship Title

Software Engineering Internship

### Location

Philadelphia, PA | Bloomfield, CT | St. Louis, MO | Denver, CO l Morris Plains, NJ l Nashville/Franklin, TN | Austin, TX | Bloomington, MN  

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by GaryZhous** [comment]
my bad, I will update this link to their specific roles
