### ISSUE TITLE
Fix "Wing" Software Engineering Intern Term

### ISSUE THREAD

**Issue by Sourabh-Kumar7** [pittcsc/Summer2023-Internships#4476]
### Link to Internship Posting

https://wing.com/careers/7653909002/?gh_jid=7653909002&utm_source=Simplify&ref=Simplify

### Company Name

Wing

### Internship Title

Software Engineering Intern

### Location

Palo Alto, CA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

Yes

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

kumar.sou@northeastern.edu

### Reason for edit

I noticed that a job listing I applied for was under the spring co-op category, but it’s actually for summer 2025. I wanted to report this so that it can be corrected to prevent confusion for other students.

**Comment by Sourabh-Kumar7** [comment]
Its there in README-Off-Season.md list

**Comment by yan-michael** [comment]
Can you double check the URL? Make sure you right click the link from the repo

**Comment by GaryZhous** [comment]
sometimes the actual link is different from the link registered on the list since link redirection might happen. you have to see the raw code of the mark down file and find the registered link!
