### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by vachik123** [pittcsc/Summer2023-Internships#4486]
### Link to Internship Posting

https://www.att.jobs/search-jobs/?ascf=[{%27key%27:%27custom_fields.ProgramCard%27,%27value%27:%27Technology%20Development%20Program%20Internship%27}]

### Company Name

AT&T

### Internship Title

Technology Development Program Internship

### Location

Middletown, NJ | Bothell, WA | Dallas, TX | Atlanta, GA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

vachik123@gmail.com

**Comment by yan-michael** [comment]
this link doesnt work
