### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by NishthaSharma-22** [pittcsc/Summer2023-Internships#4566]
### Link to Internship Posting

https://geico.wd1.myworkdayjobs.com/en-US/External/details/Software-Development-Intern_R0051950?q=software%20engineer%20intern&utm_source=Simplify&ref=Simplify

### Does this internship offer sponsorship?

None

### Is this internship still accepting applications?

No

### Permanently remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

nishthans22@gmail.com

### Reason for edit

This internship is no longer accepting applications.

**Comment by PresidentSam100** [comment]
Thank you!
