### ISSUE TITLE
New Internship: Microsoft Explore

### ISSUE THREAD

**Issue by waterkimchi** [pittcsc/Summer2023-Internships#4594]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/job/1782349/Explore-Program-Internship-Opportunities%3A-First-Year-Students%2C-Redmond

### Company Name

Microsoft

### Internship Title

Explore Program Internship Opportunities: First-Year Students

### Location

Redmond, WA

### What term(s) is this internship offered for?

Summer 2025

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

hyunsul2@uci.edu

### Extra Notes (Optional)

First-year only internship

**Comment by PresidentSam100** [comment]
Approved!
