### ISSUE TITLE
Mobile App Developer Internship (Remote) - Umee

### ISSUE THREAD

**Issue by IzzyBizzyCoding** [pittcsc/Summer2023-Internships#4694]
### Link to Internship Posting

https://forms.gle/X3HLhadHgQ3nuno19

### Company Name

Umee

### Internship Title

Mobile App Developer Intern

### Location

Fairfax, Virginia | Remote

### What term(s) is this internship offered for?

Summer 2025, Fall 2025, Winter 2025, Spring 2025

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

umee2024@gmail.com

### Extra Notes (Optional)

Harvard, Cornell, MIT, UVA, UMD students/grads who are making a social network for gyms. Looking for developers with mobile app experience. No BS, Start-up culture with our current team of 16. We're focused on building quickly and making an impact. Ideal candidates are not shy or timid—they are aggressive about deadlines, and are focused on getting things done without much supervision—no over-planning or hesitation. We're here to win.

**Comment by park-jemin** [comment]
why is it always the unpaid ones with no industry experience that ask the most lmao

**Comment by Casper-Guo** [comment]
> Voluntary position

> 6 mandatory paragraph responses in the application

> or other pertinent links such as your Git ("Java and Javascript are the same thing right?" level mistake)

> We're Harvard, Cornell, and MIT students/grads (promptly make a spelling mistake in the subsequent sentence)

> We’re focusing on fortifying and organizing existing communities of practice by encouraging active engagement and real life connection. (Tired pitch. We are going to jump in with meetup, eventbrite, kommunity, allevents, subreddits, discord servers, etc. etc.)

Who approved that form lmao
