### ISSUE TITLE
Where can we find the Fall2022-NG?

### ISSUE THREAD

**Issue by Francis1998** [pittcsc/Summer2023-Internships#818]

**Comment by jaygupt** [comment]
I'm not sure what you mean about "NG", however, there is this [list](https://github.com/bsovs/Fall2022-Internships).

**Comment by 94rain** [comment]
I think they mean 2023 New Graduates openings.

**Comment by 94rain** [comment]
I think they mean 2023 New Graduates openings (students graduate in Fall 2022 can also apply to)?

**Comment by jaygupt** [comment]
I see! Yes, I would be interested in such a list as well. I think these openings will be more prevalent in July/August onwards.

**Comment by Zmwang622** [comment]
CoderQuad set one up [here](https://github.com/coderQuad/New-Grad-Positions-2023)
