### ISSUE TITLE
Can we possibly order these by start date?

### ISSUE THREAD

**Issue by parth-commits** [pittcsc/Summer2023-Internships#837]
Currently, because different PRs are getting merged in different order, the order isnt by start date, so its hard to keep track of if anything new came up. Can we possibly add a column for posted date or something?

**Comment by JamesYL** [comment]
you could use 
![image](https://user-images.githubusercontent.com/52609399/173660924-455d45f9-d1a3-4d98-a938-75ff0f19e055.png)
this handy feature too so it sends you an email every time a new PR is merged

**Comment by parth-commits** [comment]
got it thanks!
