### ISSUE TITLE
Order posts by Date Added rather than Alphabetical

### ISSUE THREAD

**Issue by devansh289** [pittcsc/Summer2023-Internships#847]
It makes it really hard to keep track of when what posting was added. Can we maybe switch to a format where we don't order postings alphabetically but by date of addition?

**Comment by JamesYL** [comment]
#837

**Comment by rxiao8** [comment]
Would it be ideal to make/find a small program that could read in a csv file of the internships and convert it to a markdown table to paste into the README.md? The csv file can be exported from a public Excel sheet and the link posted in the README.md. In the Excel sheet we could have filters based on name, date closing, locations, and closed/open. If this is desired, I could tinker with the idea but it might take a while.

**Comment by rxiao8** [comment]
Looks interesting! We could add the date column and then in the README.md state where the user can install the plug-in.

**Comment by Zmwang622** [comment]
It should be sorted by date added, for future PRs we will be sure not to merge if its sorted alphabetically. Sorry! @owini @sim1029
