### ISSUE TITLE
Intel Link Is Not for Summer 2023 Potentially?

### ISSUE THREAD

**Issue by nicktorres12** [pittcsc/Summer2023-Internships#871]
I applied for the Intel Intern role and was rejected an hour later. I thought it was odd, since I didn't expect to hear back so soon. I checked the job summary and listing and I couldn't find where it says it was listed for Summer 2023, in fact I couldn't find the time period at all. 

Could we check it see if it's for 2023?

**Comment by chen-siyuan** [comment]
The same thing happened to me and apparently a bunch of people on reddit. However, the job is posted 11 days ago, which suggests it is likely not for 2022?

**Comment by rhit-corridg** [comment]
I applied last night and I have not been auto rejected

**Comment by matthewlkaplan** [comment]
Applied Wednesday morning and have not heard anything.

**Comment by BumbleIV** [comment]
also applied asap the link was merged into repo and got rejected day after

**Comment by ewang2002** [comment]
I applied on June 21 and got rejected 7 days later.

As @chen-siyuan said, the application was posted 11 days ago, so it's highly unlikely it's for 2022.

**Comment by matthibbs7** [comment]
I believe this posting IS in fact for Summer 2022. 

There is a post on r/csMajors where a user describes how he is actively interviewing for a Summer 2022 internship at Intel: https://www.reddit.com/r/csMajors/comments/vpz3ws/interview_at_intel_software_engineer_internship/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

This would explain why so many people are getting rejected almost instantly...

**Comment by AbdulMalikDev** [comment]
Was rejected almost instantly as well. Looks like they're looking for something specific I guess.

**Comment by parth-commits** [comment]
This is probably for summer 2023 or fall 2022 or winter 2023. Can not be for summer 2022 since half the summer term is already over. 
Are you eligible to work in the USA without visa? They say on their posting that they wont sponsor for this role. Other than that, I'm not sure, maybe some hidden requirement like GPA or something?

**Comment by salil-khanna** [comment]
i just received an interview for this role, summer 2023 !!
