### ISSUE TITLE
Only adding to the list?

### ISSUE THREAD

**Issue by jay-joo-code** [pittcsc/Summer2023-Internships#876]
There are some "express of interest" applications on the list. 

When the actual applications come out for those companies, could they be added to the list, instead of replacing the current "expression of interest"?

Based on how I'm tracking my applications, I could miss the actual application if a new item isn't added to the list.

Thanks!!

**Comment by sim1029** [comment]
I agree that these types of entries should be given a new row and appended to the list

**Comment by tendstofortytwo** [comment]
If only we as software developers were familiar with a form of table/ledger that were append-only, such that old entries could not be edited but only new ones could be added at the end. It would form something like an unbreakable "chain" of entries, and each entry could be described as a "block" containing new data...

**Comment by AbdulMalikDev** [comment]
@jay-joo-code can you share the method you're using to track your applications if you don't mind?

**Comment by sim1029** [comment]
I use this https://docs.google.com/spreadsheets/d/18wE_l5fs15MI8xhraM_Lh0dhqX4oTvwGJIYhJaKQJAY/edit?usp=sharing
