### ISSUE TITLE
Push recent additions to top rather than bottom?

### ISSUE THREAD

**Issue by matthewlkaplan** [pittcsc/Summer2023-Internships#942]
As the list of openings grows longer, might be more useful to append new additions to the top of the list rather than the bottom

**Comment by ewang2002** [comment]
A "Jump to Bottom" link is probably easier -- we can just link the "We love our contributors" section at the top and call it a day.

**Comment by Zmwang622** [comment]
jump to bottom added! great idea @ewang2002
