### ISSUE TITLE
Pixar SWE internship post leads to an empty page

### ISSUE THREAD

**Issue by BustosAndrew** [pittcsc/Summer2023-Internships#943]
After clicking the aforementioned link, then clicking the apply now button, it leads to an empty page. Just a heads up for everyone. 😄

**Comment by Zmwang622** [comment]
https://user-images.githubusercontent.com/36709118/182210579-a8f04521-182e-48f8-a039-130d7bcb5ce0.mov

**Comment by Zmwang622** [comment]
hmmmm seems to work for me, unless i'm doing something wrong?

**Comment by BraedenNorris** [comment]
@Zmwang622 You need to log in to Workday and then you'll get the 404.

**Comment by JacksonLeb** [comment]
I am also having the same issue, def something wrong with their workday page.

**Comment by BustosAndrew** [comment]
I have a feeling they didn't actually post the job yet.

**Comment by Zmwang622** [comment]
will mark as broken for now

**Comment by anjaligupta0621** [comment]
I couldn't see the job on their Careers page as well

**Comment by gmacheta** [comment]
the error started yesterday, two days ago I could access the page and read the job description.

**Comment by angelh52** [comment]
Please refer to this link: https://pixar.wd5.myworkdayjobs.com/Pixar_External_Internships/details/Software-Engineer-Intern--Renderman---Summer-2023_R-03416-1

**Comment by sanskarfc** [comment]
The above link works fine.

**Comment by BustosAndrew** [comment]
Yes it works now thanks for the update.
