### ISSUE TITLE
Sentry.io has no open internships

### ISSUE THREAD

**Issue by kylediaz** [pittcsc/Summer2023-Internships#961]
https://sentry.io/careers/internships/
This link would be better because it doesn't look like there's a direct link to the internships page from the current link.
Also
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/35979917/182682306-d2af1edc-d239-49da-82da-41ad12dcafd8.png">
? Is it only me

**Comment by rewong03** [comment]
Huh that's strange. I went to the site immediately after the PR to the repo was made and there were open roles. I was able to apply and even got confirmation email + email requesting me to make a profile on another site

**Comment by Zmwang622** [comment]
the roles seem to be open on my end, i replaced the link we have on the repo though, better to link to the internships page than the generic careers
