### ISSUE TITLE
Add DRW

### ISSUE THREAD

**Issue by imoiwm** [pittcsc/Summer2023-Internships#970]
Don't know how to best contribute directly to the list, but DRW is also open for Summer 2023.
Note the following links are US (mostly Chicago) while there is a separate link for each one specifically for London.

https://drw.com/work-at-drw/category/campus/

[Quantitative Research Intern (Masters/PhD)](https://drw.com/work-at-drw/job/quantitative-research-intern-2301002/)
[Quantitative Trading Analyst Intern](https://drw.com/work-at-drw/job/quantitative-trading-analyst-intern-2302675/)
[Software Developer Intern](https://drw.com/work-at-drw/job/software-developer-intern-2302636/)

**Comment by Zmwang622** [comment]
Nice work!
