### ISSUE TITLE
Sentry Internship US locations are unavailable

### ISSUE THREAD

**Issue by beetisushruth** [pittcsc/Summer2023-Internships#975]
Sentry Internship doesn't have any openings in US, readme needs to be updated.

![Screen Shot 2022-08-05 at 2 59 16 PM](https://user-images.githubusercontent.com/46922446/183143713-cc69e751-b5bc-46f0-b99d-0774cfd730e2.png)

**Comment by nkalupahana** [comment]
I applied to the US version (SF, CA) just a few days ago. Did it... already close? 👀 

It looks like this is still open, at least: https://www.untapped.io/app/discover/jobs/a/a/bc1ab5f1-1381-49d9-b2b6-698b74de49ba

**Comment by SavarJ** [comment]
Yeah looks like it got closed 😏
